/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package cn.gatesma.desirefu.controller.api.generate;

import cn.gatesma.desirefu.domain.api.generate.AddCompetitionRequest;
import cn.gatesma.desirefu.domain.api.generate.AddCompetitionRet;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@Api(value = "Competition", tags={ "比赛", }, description = "the Competition API")
public interface CompetitionApi {

    @ApiOperation(value = "创建比赛信息", nickname = "addCompetition", notes = "创建比赛信息", response = AddCompetitionRet.class, tags={ "比赛", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = AddCompetitionRet.class),
        @ApiResponse(code = 400, message = "Invalid RequestBody supplied"),
        @ApiResponse(code = 404, message = "RequestBody not found") })
    @RequestMapping(value = "/competition/add",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<AddCompetitionRet> addCompetition(@ApiParam(value = "创建账号" ,required=true )  @Valid @RequestBody AddCompetitionRequest body);

}
