/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package cn.gatesma.desirefu.controller.api.generate;

import cn.gatesma.desirefu.domain.api.generate.CanLoginAccountRequest;
import cn.gatesma.desirefu.domain.api.generate.CanLoginAccountRet;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@Api(value = "Login", tags={ "登陆", }, description = "the Login API")
public interface LoginApi {

    @ApiOperation(value = "查询一个用户可以登录的账号", nickname = "canLoginAccount", notes = "查询一个用户可以登录的账号", response = CanLoginAccountRet.class, tags={ "登陆", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CanLoginAccountRet.class),
        @ApiResponse(code = 400, message = "Invalid RequestBody supplied"),
        @ApiResponse(code = 404, message = "RequestBody not found") })
    @RequestMapping(value = "/login/can_login_account",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<CanLoginAccountRet> canLoginAccount(@ApiParam(value = "" ,required=true )  @Valid @RequestBody CanLoginAccountRequest body);

}
