/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package cn.gatesma.desirefu.controller.api.generate;

import cn.gatesma.desirefu.domain.api.generate.AddOrganizeApplicationRequest;
import cn.gatesma.desirefu.domain.api.generate.AddOrganizeApplicationRet;
import cn.gatesma.desirefu.domain.api.generate.SelectOrganizeApplicationRequest;
import cn.gatesma.desirefu.domain.api.generate.SelectOrganizeApplicationRet;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@Api(value = "OrganizeAccountApplication", tags={ "队伍", }, description = "the OrganizeAccountApplication API")
public interface OrganizeAccountApplicationApi {

    @ApiOperation(value = "发起加入组织请求", nickname = "addOrganizeApplication", notes = "创建组织，返回\"账号ID\"", response = AddOrganizeApplicationRet.class, tags={ "队伍", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = AddOrganizeApplicationRet.class),
        @ApiResponse(code = 400, message = "Invalid RequestBody supplied"),
        @ApiResponse(code = 404, message = "RequestBody not found") })
    @RequestMapping(value = "/organize_application/add",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<AddOrganizeApplicationRet> addOrganizeApplication(@ApiParam(value = "创建账号" ,required=true )  @Valid @RequestBody AddOrganizeApplicationRequest body);


    @ApiOperation(value = "获取请求信息", nickname = "selectOrganizeApplication", notes = "获取请求信息", response = SelectOrganizeApplicationRet.class, tags={ "队伍", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = SelectOrganizeApplicationRet.class),
        @ApiResponse(code = 400, message = "Invalid RequestBody supplied"),
        @ApiResponse(code = 404, message = "RequestBody not found") })
    @RequestMapping(value = "/organize_application/select_scroll",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<SelectOrganizeApplicationRet> selectOrganizeApplication(@ApiParam(value = "" ,required=true )  @Valid @RequestBody SelectOrganizeApplicationRequest body);

}
