/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package cn.gatesma.desirefu.controller.api.generate;

import org.springframework.core.io.Resource;
import cn.gatesma.desirefu.domain.api.generate.UploadFileRet;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@Api(value = "Upload", tags={ "上传", }, description = "the Upload API")
public interface UploadApi {

    @ApiOperation(value = "", nickname = "uploadFile", notes = "文件上传", response = UploadFileRet.class, tags={ "上传", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Ok", response = UploadFileRet.class),
        @ApiResponse(code = 400, message = "Invalid RequestBody supplied"),
        @ApiResponse(code = 404, message = "RequestBody not found") })
    @RequestMapping(value = "/upload/upload_file",
        produces = { "application/json" }, 
        consumes = { "multipart/form-data" },
        method = RequestMethod.POST)
    ResponseEntity<UploadFileRet> uploadFile(@ApiParam(value = "", required=true) @RequestParam(value="account_id", required=true)  Long accountId,
                                             @ApiParam(value = "", required=true) @RequestParam(value="account_type", required=true)  Integer accountType,
                                             @ApiParam(value = "", required=false) @RequestParam(value="file_name", required=false)  String fileName,
                                             @ApiParam(value = "", required=true) @RequestParam(value="file_type", required=true)  String fileType,
                                             @ApiParam(value = "file detail") @Valid @RequestPart("file") MultipartFile upfile);

}
