/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.daos;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Account_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.Account_Record;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account_Dao extends DAOImpl<Account_Record, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_, Long> {

    /**
     * Create a new Account_Dao without any configuration
     */
    public Account_Dao() {
        super(Account_.ACCOUNT_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_.class);
    }

    /**
     * Create a new Account_Dao with an attached configuration
     */
    public Account_Dao(Configuration configuration) {
        super(Account_.ACCOUNT_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_ object) {
        return object.getAccountid();
    }

    /**
     * Fetch records that have <code>accountId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_> fetchByAccountid(Long... values) {
        return fetch(Account_.ACCOUNT_.ACCOUNTID, values);
    }

    /**
     * Fetch a unique record that has <code>accountId = value</code>
     */
    public cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_ fetchOneByAccountid(Long value) {
        return fetchOne(Account_.ACCOUNT_.ACCOUNTID, value);
    }

    /**
     * Fetch records that have <code>accountType IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_> fetchByAccounttype(Integer... values) {
        return fetch(Account_.ACCOUNT_.ACCOUNTTYPE, values);
    }

    /**
     * Fetch records that have <code>nickName IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_> fetchByNickname(String... values) {
        return fetch(Account_.ACCOUNT_.NICKNAME, values);
    }

    /**
     * Fetch records that have <code>accountStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_> fetchByAccountstatus(Integer... values) {
        return fetch(Account_.ACCOUNT_.ACCOUNTSTATUS, values);
    }

    /**
     * Fetch records that have <code>approvalStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_> fetchByApprovalstatus(Integer... values) {
        return fetch(Account_.ACCOUNT_.APPROVALSTATUS, values);
    }

    /**
     * Fetch records that have <code>memo IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_> fetchByMemo(String... values) {
        return fetch(Account_.ACCOUNT_.MEMO, values);
    }

    /**
     * Fetch records that have <code>auditUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_> fetchByAudituserid(Long... values) {
        return fetch(Account_.ACCOUNT_.AUDITUSERID, values);
    }

    /**
     * Fetch records that have <code>auditMsg IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_> fetchByAuditmsg(String... values) {
        return fetch(Account_.ACCOUNT_.AUDITMSG, values);
    }

    /**
     * Fetch records that have <code>auditedTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_> fetchByAuditedtime(Timestamp... values) {
        return fetch(Account_.ACCOUNT_.AUDITEDTIME, values);
    }

    /**
     * Fetch records that have <code>createdUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_> fetchByCreateduserid(Long... values) {
        return fetch(Account_.ACCOUNT_.CREATEDUSERID, values);
    }

    /**
     * Fetch records that have <code>createdTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_> fetchByCreatedtime(Timestamp... values) {
        return fetch(Account_.ACCOUNT_.CREATEDTIME, values);
    }

    /**
     * Fetch records that have <code>deleteStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_> fetchByDeletestatus(Integer... values) {
        return fetch(Account_.ACCOUNT_.DELETESTATUS, values);
    }

    /**
     * Fetch records that have <code>lastModifiedUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_> fetchByLastmodifieduserid(Long... values) {
        return fetch(Account_.ACCOUNT_.LASTMODIFIEDUSERID, values);
    }

    /**
     * Fetch records that have <code>lastModifiedTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Account_> fetchByLastmodifiedtime(Timestamp... values) {
        return fetch(Account_.ACCOUNT_.LASTMODIFIEDTIME, values);
    }
}
