/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.daos;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Collect_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.Collect_Record;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 收藏表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Collect_Dao extends DAOImpl<Collect_Record, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Collect_, Long> {

    /**
     * Create a new Collect_Dao without any configuration
     */
    public Collect_Dao() {
        super(Collect_.COLLECT_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Collect_.class);
    }

    /**
     * Create a new Collect_Dao with an attached configuration
     */
    public Collect_Dao(Configuration configuration) {
        super(Collect_.COLLECT_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Collect_.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Collect_ object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Collect_> fetchById(Long... values) {
        return fetch(Collect_.COLLECT_.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Collect_ fetchOneById(Long value) {
        return fetchOne(Collect_.COLLECT_.ID, value);
    }

    /**
     * Fetch records that have <code>accountId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Collect_> fetchByAccountid(Long... values) {
        return fetch(Collect_.COLLECT_.ACCOUNTID, values);
    }

    /**
     * Fetch records that have <code>competitionId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Collect_> fetchByCompetitionid(Long... values) {
        return fetch(Collect_.COLLECT_.COMPETITIONID, values);
    }

    /**
     * Fetch records that have <code>createdTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Collect_> fetchByCreatedtime(Timestamp... values) {
        return fetch(Collect_.COLLECT_.CREATEDTIME, values);
    }

    /**
     * Fetch records that have <code>deleteStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Collect_> fetchByDeletestatus(Integer... values) {
        return fetch(Collect_.COLLECT_.DELETESTATUS, values);
    }

    /**
     * Fetch records that have <code>lastModifiedTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Collect_> fetchByLastmodifiedtime(Timestamp... values) {
        return fetch(Collect_.COLLECT_.LASTMODIFIEDTIME, values);
    }
}
