/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.daos;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Competition_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.Competition_Record;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 比赛
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Competition_Dao extends DAOImpl<Competition_Record, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_, Long> {

    /**
     * Create a new Competition_Dao without any configuration
     */
    public Competition_Dao() {
        super(Competition_.COMPETITION_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_.class);
    }

    /**
     * Create a new Competition_Dao with an attached configuration
     */
    public Competition_Dao(Configuration configuration) {
        super(Competition_.COMPETITION_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_ object) {
        return object.getCompetitionid();
    }

    /**
     * Fetch records that have <code>competitionId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_> fetchByCompetitionid(Long... values) {
        return fetch(Competition_.COMPETITION_.COMPETITIONID, values);
    }

    /**
     * Fetch a unique record that has <code>competitionId = value</code>
     */
    public cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_ fetchOneByCompetitionid(Long value) {
        return fetchOne(Competition_.COMPETITION_.COMPETITIONID, value);
    }

    /**
     * Fetch records that have <code>accountId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_> fetchByAccountid(Long... values) {
        return fetch(Competition_.COMPETITION_.ACCOUNTID, values);
    }

    /**
     * Fetch records that have <code>accountType IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_> fetchByAccounttype(Integer... values) {
        return fetch(Competition_.COMPETITION_.ACCOUNTTYPE, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_> fetchByType(Integer... values) {
        return fetch(Competition_.COMPETITION_.TYPE, values);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_> fetchByTitle(String... values) {
        return fetch(Competition_.COMPETITION_.TITLE, values);
    }

    /**
     * Fetch records that have <code>founder IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_> fetchByFounder(String... values) {
        return fetch(Competition_.COMPETITION_.FOUNDER, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_> fetchByContent(String... values) {
        return fetch(Competition_.COMPETITION_.CONTENT, values);
    }

    /**
     * Fetch records that have <code>pv IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_> fetchByPv(Integer... values) {
        return fetch(Competition_.COMPETITION_.PV, values);
    }

    /**
     * Fetch records that have <code>beginTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_> fetchByBegintime(Timestamp... values) {
        return fetch(Competition_.COMPETITION_.BEGINTIME, values);
    }

    /**
     * Fetch records that have <code>endTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_> fetchByEndtime(Timestamp... values) {
        return fetch(Competition_.COMPETITION_.ENDTIME, values);
    }

    /**
     * Fetch records that have <code>deleteStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_> fetchByDeletestatus(Integer... values) {
        return fetch(Competition_.COMPETITION_.DELETESTATUS, values);
    }

    /**
     * Fetch records that have <code>createdUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_> fetchByCreateduserid(Long... values) {
        return fetch(Competition_.COMPETITION_.CREATEDUSERID, values);
    }

    /**
     * Fetch records that have <code>createdTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_> fetchByCreatedtime(Timestamp... values) {
        return fetch(Competition_.COMPETITION_.CREATEDTIME, values);
    }

    /**
     * Fetch records that have <code>lastModifiedUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_> fetchByLastmodifieduserid(Long... values) {
        return fetch(Competition_.COMPETITION_.LASTMODIFIEDUSERID, values);
    }

    /**
     * Fetch records that have <code>lastModifiedTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competition_> fetchByLastmodifiedtime(Timestamp... values) {
        return fetch(Competition_.COMPETITION_.LASTMODIFIEDTIME, values);
    }
}
