/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.daos;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Competitionvisible_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.Competitionvisible_Record;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * 高校可见比赛表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Competitionvisible_Dao extends DAOImpl<Competitionvisible_Record, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitionvisible_, Record2<Long, Integer>> {

    /**
     * Create a new Competitionvisible_Dao without any configuration
     */
    public Competitionvisible_Dao() {
        super(Competitionvisible_.COMPETITIONVISIBLE_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitionvisible_.class);
    }

    /**
     * Create a new Competitionvisible_Dao with an attached configuration
     */
    public Competitionvisible_Dao(Configuration configuration) {
        super(Competitionvisible_.COMPETITIONVISIBLE_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitionvisible_.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Long, Integer> getId(cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitionvisible_ object) {
        return compositeKeyRecord(object.getCompetitionid(), object.getCollegeid());
    }

    /**
     * Fetch records that have <code>collegeId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitionvisible_> fetchByCollegeid(Integer... values) {
        return fetch(Competitionvisible_.COMPETITIONVISIBLE_.COLLEGEID, values);
    }

    /**
     * Fetch records that have <code>competitionId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitionvisible_> fetchByCompetitionid(Long... values) {
        return fetch(Competitionvisible_.COMPETITIONVISIBLE_.COMPETITIONID, values);
    }

    /**
     * Fetch records that have <code>deleteStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitionvisible_> fetchByDeletestatus(Integer... values) {
        return fetch(Competitionvisible_.COMPETITIONVISIBLE_.DELETESTATUS, values);
    }

    /**
     * Fetch records that have <code>createdTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitionvisible_> fetchByCreatedtime(Timestamp... values) {
        return fetch(Competitionvisible_.COMPETITIONVISIBLE_.CREATEDTIME, values);
    }

    /**
     * Fetch records that have <code>lastModifiedTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitionvisible_> fetchByLastmodifiedtime(Timestamp... values) {
        return fetch(Competitionvisible_.COMPETITIONVISIBLE_.LASTMODIFIEDTIME, values);
    }
}
