/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.daos;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Competitioncreatoraccount_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.Competitioncreatoraccount_Record;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 比赛创建者账号
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Competitioncreatoraccount_Dao extends DAOImpl<Competitioncreatoraccount_Record, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitioncreatoraccount_, Long> {

    /**
     * Create a new Competitioncreatoraccount_Dao without any configuration
     */
    public Competitioncreatoraccount_Dao() {
        super(Competitioncreatoraccount_.COMPETITIONCREATORACCOUNT_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitioncreatoraccount_.class);
    }

    /**
     * Create a new Competitioncreatoraccount_Dao with an attached configuration
     */
    public Competitioncreatoraccount_Dao(Configuration configuration) {
        super(Competitioncreatoraccount_.COMPETITIONCREATORACCOUNT_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitioncreatoraccount_.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitioncreatoraccount_ object) {
        return object.getAccountid();
    }

    /**
     * Fetch records that have <code>accountId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitioncreatoraccount_> fetchByAccountid(Long... values) {
        return fetch(Competitioncreatoraccount_.COMPETITIONCREATORACCOUNT_.ACCOUNTID, values);
    }

    /**
     * Fetch a unique record that has <code>accountId = value</code>
     */
    public cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitioncreatoraccount_ fetchOneByAccountid(Long value) {
        return fetchOne(Competitioncreatoraccount_.COMPETITIONCREATORACCOUNT_.ACCOUNTID, value);
    }

    /**
     * Fetch records that have <code>accountType IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitioncreatoraccount_> fetchByAccounttype(Integer... values) {
        return fetch(Competitioncreatoraccount_.COMPETITIONCREATORACCOUNT_.ACCOUNTTYPE, values);
    }

    /**
     * Fetch records that have <code>author IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitioncreatoraccount_> fetchByAuthor(String... values) {
        return fetch(Competitioncreatoraccount_.COMPETITIONCREATORACCOUNT_.AUTHOR, values);
    }

    /**
     * Fetch records that have <code>createdUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitioncreatoraccount_> fetchByCreateduserid(Long... values) {
        return fetch(Competitioncreatoraccount_.COMPETITIONCREATORACCOUNT_.CREATEDUSERID, values);
    }

    /**
     * Fetch records that have <code>createdTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitioncreatoraccount_> fetchByCreatedtime(Timestamp... values) {
        return fetch(Competitioncreatoraccount_.COMPETITIONCREATORACCOUNT_.CREATEDTIME, values);
    }

    /**
     * Fetch records that have <code>deleteStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitioncreatoraccount_> fetchByDeletestatus(Integer... values) {
        return fetch(Competitioncreatoraccount_.COMPETITIONCREATORACCOUNT_.DELETESTATUS, values);
    }

    /**
     * Fetch records that have <code>lastModifiedUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitioncreatoraccount_> fetchByLastmodifieduserid(Long... values) {
        return fetch(Competitioncreatoraccount_.COMPETITIONCREATORACCOUNT_.LASTMODIFIEDUSERID, values);
    }

    /**
     * Fetch records that have <code>lastModifiedTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Competitioncreatoraccount_> fetchByLastmodifiedtime(Timestamp... values) {
        return fetch(Competitioncreatoraccount_.COMPETITIONCREATORACCOUNT_.LASTMODIFIEDTIME, values);
    }
}
