/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.daos;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Message_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.Message_Record;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 消息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Message_Dao extends DAOImpl<Message_Record, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Message_, Long> {

    /**
     * Create a new Message_Dao without any configuration
     */
    public Message_Dao() {
        super(Message_.MESSAGE_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Message_.class);
    }

    /**
     * Create a new Message_Dao with an attached configuration
     */
    public Message_Dao(Configuration configuration) {
        super(Message_.MESSAGE_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Message_.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Message_ object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Message_> fetchById(Long... values) {
        return fetch(Message_.MESSAGE_.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Message_ fetchOneById(Long value) {
        return fetchOne(Message_.MESSAGE_.ID, value);
    }

    /**
     * Fetch records that have <code>accountId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Message_> fetchByAccountid(Long... values) {
        return fetch(Message_.MESSAGE_.ACCOUNTID, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Message_> fetchByType(Integer... values) {
        return fetch(Message_.MESSAGE_.TYPE, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Message_> fetchByContent(String... values) {
        return fetch(Message_.MESSAGE_.CONTENT, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Message_> fetchByStatus(Integer... values) {
        return fetch(Message_.MESSAGE_.STATUS, values);
    }

    /**
     * Fetch records that have <code>createdTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Message_> fetchByCreatedtime(Timestamp... values) {
        return fetch(Message_.MESSAGE_.CREATEDTIME, values);
    }

    /**
     * Fetch records that have <code>deleteStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Message_> fetchByDeletestatus(Integer... values) {
        return fetch(Message_.MESSAGE_.DELETESTATUS, values);
    }

    /**
     * Fetch records that have <code>lastModifiedTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Message_> fetchByLastmodifiedtime(Timestamp... values) {
        return fetch(Message_.MESSAGE_.LASTMODIFIEDTIME, values);
    }
}
