/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.daos;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Normalaccount_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.Normalaccount_Record;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Normalaccount_Dao extends DAOImpl<Normalaccount_Record, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_, Long> {

    /**
     * Create a new Normalaccount_Dao without any configuration
     */
    public Normalaccount_Dao() {
        super(Normalaccount_.NORMALACCOUNT_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_.class);
    }

    /**
     * Create a new Normalaccount_Dao with an attached configuration
     */
    public Normalaccount_Dao(Configuration configuration) {
        super(Normalaccount_.NORMALACCOUNT_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_ object) {
        return object.getAccountid();
    }

    /**
     * Fetch records that have <code>accountId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_> fetchByAccountid(Long... values) {
        return fetch(Normalaccount_.NORMALACCOUNT_.ACCOUNTID, values);
    }

    /**
     * Fetch a unique record that has <code>accountId = value</code>
     */
    public cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_ fetchOneByAccountid(Long value) {
        return fetchOne(Normalaccount_.NORMALACCOUNT_.ACCOUNTID, value);
    }

    /**
     * Fetch records that have <code>accountType IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_> fetchByAccounttype(Integer... values) {
        return fetch(Normalaccount_.NORMALACCOUNT_.ACCOUNTTYPE, values);
    }

    /**
     * Fetch records that have <code>collegeId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_> fetchByCollegeid(Integer... values) {
        return fetch(Normalaccount_.NORMALACCOUNT_.COLLEGEID, values);
    }

    /**
     * Fetch records that have <code>departmentId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_> fetchByDepartmentid(Integer... values) {
        return fetch(Normalaccount_.NORMALACCOUNT_.DEPARTMENTID, values);
    }

    /**
     * Fetch records that have <code>major IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_> fetchByMajor(String... values) {
        return fetch(Normalaccount_.NORMALACCOUNT_.MAJOR, values);
    }

    /**
     * Fetch records that have <code>stuId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_> fetchByStuid(String... values) {
        return fetch(Normalaccount_.NORMALACCOUNT_.STUID, values);
    }

    /**
     * Fetch records that have <code>createdUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_> fetchByCreateduserid(Long... values) {
        return fetch(Normalaccount_.NORMALACCOUNT_.CREATEDUSERID, values);
    }

    /**
     * Fetch records that have <code>createdTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_> fetchByCreatedtime(Timestamp... values) {
        return fetch(Normalaccount_.NORMALACCOUNT_.CREATEDTIME, values);
    }

    /**
     * Fetch records that have <code>deleteStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_> fetchByDeletestatus(Integer... values) {
        return fetch(Normalaccount_.NORMALACCOUNT_.DELETESTATUS, values);
    }

    /**
     * Fetch records that have <code>lastModifiedUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_> fetchByLastmodifieduserid(Long... values) {
        return fetch(Normalaccount_.NORMALACCOUNT_.LASTMODIFIEDUSERID, values);
    }

    /**
     * Fetch records that have <code>lastModifiedTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Normalaccount_> fetchByLastmodifiedtime(Timestamp... values) {
        return fetch(Normalaccount_.NORMALACCOUNT_.LASTMODIFIEDTIME, values);
    }
}
