/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.daos;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Notification_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.Notification_Record;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 公告
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notification_Dao extends DAOImpl<Notification_Record, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Notification_, Integer> {

    /**
     * Create a new Notification_Dao without any configuration
     */
    public Notification_Dao() {
        super(Notification_.NOTIFICATION_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Notification_.class);
    }

    /**
     * Create a new Notification_Dao with an attached configuration
     */
    public Notification_Dao(Configuration configuration) {
        super(Notification_.NOTIFICATION_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Notification_.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Notification_ object) {
        return object.getNoticeid();
    }

    /**
     * Fetch records that have <code>noticeId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Notification_> fetchByNoticeid(Integer... values) {
        return fetch(Notification_.NOTIFICATION_.NOTICEID, values);
    }

    /**
     * Fetch a unique record that has <code>noticeId = value</code>
     */
    public cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Notification_ fetchOneByNoticeid(Integer value) {
        return fetchOne(Notification_.NOTIFICATION_.NOTICEID, value);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Notification_> fetchByType(Integer... values) {
        return fetch(Notification_.NOTIFICATION_.TYPE, values);
    }

    /**
     * Fetch records that have <code>frontImg IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Notification_> fetchByFrontimg(String... values) {
        return fetch(Notification_.NOTIFICATION_.FRONTIMG, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Notification_> fetchByStatus(Integer... values) {
        return fetch(Notification_.NOTIFICATION_.STATUS, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Notification_> fetchByContent(String... values) {
        return fetch(Notification_.NOTIFICATION_.CONTENT, values);
    }

    /**
     * Fetch records that have <code>deleteStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Notification_> fetchByDeletestatus(Integer... values) {
        return fetch(Notification_.NOTIFICATION_.DELETESTATUS, values);
    }

    /**
     * Fetch records that have <code>createdTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Notification_> fetchByCreatedtime(Timestamp... values) {
        return fetch(Notification_.NOTIFICATION_.CREATEDTIME, values);
    }

    /**
     * Fetch records that have <code>lastModifiedTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Notification_> fetchByLastmodifiedtime(Timestamp... values) {
        return fetch(Notification_.NOTIFICATION_.LASTMODIFIEDTIME, values);
    }
}
