/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.daos;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Organizeaccountapplication_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.Organizeaccountapplication_Record;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 圈子申请信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organizeaccountapplication_Dao extends DAOImpl<Organizeaccountapplication_Record, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountapplication_, Long> {

    /**
     * Create a new Organizeaccountapplication_Dao without any configuration
     */
    public Organizeaccountapplication_Dao() {
        super(Organizeaccountapplication_.ORGANIZEACCOUNTAPPLICATION_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountapplication_.class);
    }

    /**
     * Create a new Organizeaccountapplication_Dao with an attached configuration
     */
    public Organizeaccountapplication_Dao(Configuration configuration) {
        super(Organizeaccountapplication_.ORGANIZEACCOUNTAPPLICATION_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountapplication_.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountapplication_ object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountapplication_> fetchById(Long... values) {
        return fetch(Organizeaccountapplication_.ORGANIZEACCOUNTAPPLICATION_.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountapplication_ fetchOneById(Long value) {
        return fetchOne(Organizeaccountapplication_.ORGANIZEACCOUNTAPPLICATION_.ID, value);
    }

    /**
     * Fetch records that have <code>organizeId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountapplication_> fetchByOrganizeid(Long... values) {
        return fetch(Organizeaccountapplication_.ORGANIZEACCOUNTAPPLICATION_.ORGANIZEID, values);
    }

    /**
     * Fetch records that have <code>accountId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountapplication_> fetchByAccountid(Long... values) {
        return fetch(Organizeaccountapplication_.ORGANIZEACCOUNTAPPLICATION_.ACCOUNTID, values);
    }

    /**
     * Fetch records that have <code>accountType IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountapplication_> fetchByAccounttype(Integer... values) {
        return fetch(Organizeaccountapplication_.ORGANIZEACCOUNTAPPLICATION_.ACCOUNTTYPE, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountapplication_> fetchByStatus(Integer... values) {
        return fetch(Organizeaccountapplication_.ORGANIZEACCOUNTAPPLICATION_.STATUS, values);
    }

    /**
     * Fetch records that have <code>createdUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountapplication_> fetchByCreateduserid(Long... values) {
        return fetch(Organizeaccountapplication_.ORGANIZEACCOUNTAPPLICATION_.CREATEDUSERID, values);
    }

    /**
     * Fetch records that have <code>createdTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountapplication_> fetchByCreatedtime(Timestamp... values) {
        return fetch(Organizeaccountapplication_.ORGANIZEACCOUNTAPPLICATION_.CREATEDTIME, values);
    }

    /**
     * Fetch records that have <code>deleteStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountapplication_> fetchByDeletestatus(Integer... values) {
        return fetch(Organizeaccountapplication_.ORGANIZEACCOUNTAPPLICATION_.DELETESTATUS, values);
    }

    /**
     * Fetch records that have <code>lastModifiedUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountapplication_> fetchByLastmodifieduserid(Long... values) {
        return fetch(Organizeaccountapplication_.ORGANIZEACCOUNTAPPLICATION_.LASTMODIFIEDUSERID, values);
    }

    /**
     * Fetch records that have <code>lastModifiedTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountapplication_> fetchByLastmodifiedtime(Timestamp... values) {
        return fetch(Organizeaccountapplication_.ORGANIZEACCOUNTAPPLICATION_.LASTMODIFIEDTIME, values);
    }
}
