/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.daos;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Organizeaccountrelation_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.Organizeaccountrelation_Record;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * OrganizeAccount关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organizeaccountrelation_Dao extends DAOImpl<Organizeaccountrelation_Record, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountrelation_, Long> {

    /**
     * Create a new Organizeaccountrelation_Dao without any configuration
     */
    public Organizeaccountrelation_Dao() {
        super(Organizeaccountrelation_.ORGANIZEACCOUNTRELATION_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountrelation_.class);
    }

    /**
     * Create a new Organizeaccountrelation_Dao with an attached configuration
     */
    public Organizeaccountrelation_Dao(Configuration configuration) {
        super(Organizeaccountrelation_.ORGANIZEACCOUNTRELATION_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountrelation_.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountrelation_ object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountrelation_> fetchById(Long... values) {
        return fetch(Organizeaccountrelation_.ORGANIZEACCOUNTRELATION_.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountrelation_ fetchOneById(Long value) {
        return fetchOne(Organizeaccountrelation_.ORGANIZEACCOUNTRELATION_.ID, value);
    }

    /**
     * Fetch records that have <code>organizeId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountrelation_> fetchByOrganizeid(Long... values) {
        return fetch(Organizeaccountrelation_.ORGANIZEACCOUNTRELATION_.ORGANIZEID, values);
    }

    /**
     * Fetch records that have <code>accountId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountrelation_> fetchByAccountid(Long... values) {
        return fetch(Organizeaccountrelation_.ORGANIZEACCOUNTRELATION_.ACCOUNTID, values);
    }

    /**
     * Fetch records that have <code>accountType IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountrelation_> fetchByAccounttype(Integer... values) {
        return fetch(Organizeaccountrelation_.ORGANIZEACCOUNTRELATION_.ACCOUNTTYPE, values);
    }

    /**
     * Fetch records that have <code>isOwnerAccount IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountrelation_> fetchByIsowneraccount(Integer... values) {
        return fetch(Organizeaccountrelation_.ORGANIZEACCOUNTRELATION_.ISOWNERACCOUNT, values);
    }

    /**
     * Fetch records that have <code>createdUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountrelation_> fetchByCreateduserid(Long... values) {
        return fetch(Organizeaccountrelation_.ORGANIZEACCOUNTRELATION_.CREATEDUSERID, values);
    }

    /**
     * Fetch records that have <code>createdTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountrelation_> fetchByCreatedtime(Timestamp... values) {
        return fetch(Organizeaccountrelation_.ORGANIZEACCOUNTRELATION_.CREATEDTIME, values);
    }

    /**
     * Fetch records that have <code>deleteStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountrelation_> fetchByDeletestatus(Integer... values) {
        return fetch(Organizeaccountrelation_.ORGANIZEACCOUNTRELATION_.DELETESTATUS, values);
    }

    /**
     * Fetch records that have <code>lastModifiedUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountrelation_> fetchByLastmodifieduserid(Long... values) {
        return fetch(Organizeaccountrelation_.ORGANIZEACCOUNTRELATION_.LASTMODIFIEDUSERID, values);
    }

    /**
     * Fetch records that have <code>lastModifiedTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Organizeaccountrelation_> fetchByLastmodifiedtime(Timestamp... values) {
        return fetch(Organizeaccountrelation_.ORGANIZEACCOUNTRELATION_.LASTMODIFIEDTIME, values);
    }
}
