/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.daos;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Rootaccount_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.Rootaccount_Record;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * ROOT账号
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rootaccount_Dao extends DAOImpl<Rootaccount_Record, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Rootaccount_, Long> {

    /**
     * Create a new Rootaccount_Dao without any configuration
     */
    public Rootaccount_Dao() {
        super(Rootaccount_.ROOTACCOUNT_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Rootaccount_.class);
    }

    /**
     * Create a new Rootaccount_Dao with an attached configuration
     */
    public Rootaccount_Dao(Configuration configuration) {
        super(Rootaccount_.ROOTACCOUNT_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Rootaccount_.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Rootaccount_ object) {
        return object.getAccountid();
    }

    /**
     * Fetch records that have <code>accountId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Rootaccount_> fetchByAccountid(Long... values) {
        return fetch(Rootaccount_.ROOTACCOUNT_.ACCOUNTID, values);
    }

    /**
     * Fetch a unique record that has <code>accountId = value</code>
     */
    public cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Rootaccount_ fetchOneByAccountid(Long value) {
        return fetchOne(Rootaccount_.ROOTACCOUNT_.ACCOUNTID, value);
    }

    /**
     * Fetch records that have <code>accountType IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Rootaccount_> fetchByAccounttype(Integer... values) {
        return fetch(Rootaccount_.ROOTACCOUNT_.ACCOUNTTYPE, values);
    }

    /**
     * Fetch records that have <code>createdUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Rootaccount_> fetchByCreateduserid(Long... values) {
        return fetch(Rootaccount_.ROOTACCOUNT_.CREATEDUSERID, values);
    }

    /**
     * Fetch records that have <code>createdTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Rootaccount_> fetchByCreatedtime(Timestamp... values) {
        return fetch(Rootaccount_.ROOTACCOUNT_.CREATEDTIME, values);
    }

    /**
     * Fetch records that have <code>deleteStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Rootaccount_> fetchByDeletestatus(Integer... values) {
        return fetch(Rootaccount_.ROOTACCOUNT_.DELETESTATUS, values);
    }

    /**
     * Fetch records that have <code>lastModifiedUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Rootaccount_> fetchByLastmodifieduserid(Long... values) {
        return fetch(Rootaccount_.ROOTACCOUNT_.LASTMODIFIEDUSERID, values);
    }

    /**
     * Fetch records that have <code>lastModifiedTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Rootaccount_> fetchByLastmodifiedtime(Timestamp... values) {
        return fetch(Rootaccount_.ROOTACCOUNT_.LASTMODIFIEDTIME, values);
    }
}
