/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.daos;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Uploadfile_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.Uploadfile_Record;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 文件上传表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Uploadfile_Dao extends DAOImpl<Uploadfile_Record, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Uploadfile_, Integer> {

    /**
     * Create a new Uploadfile_Dao without any configuration
     */
    public Uploadfile_Dao() {
        super(Uploadfile_.UPLOADFILE_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Uploadfile_.class);
    }

    /**
     * Create a new Uploadfile_Dao with an attached configuration
     */
    public Uploadfile_Dao(Configuration configuration) {
        super(Uploadfile_.UPLOADFILE_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Uploadfile_.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Uploadfile_ object) {
        return object.getFileid();
    }

    /**
     * Fetch records that have <code>fileId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Uploadfile_> fetchByFileid(Integer... values) {
        return fetch(Uploadfile_.UPLOADFILE_.FILEID, values);
    }

    /**
     * Fetch a unique record that has <code>fileId = value</code>
     */
    public cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Uploadfile_ fetchOneByFileid(Integer value) {
        return fetchOne(Uploadfile_.UPLOADFILE_.FILEID, value);
    }

    /**
     * Fetch records that have <code>fileType IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Uploadfile_> fetchByFiletype(String... values) {
        return fetch(Uploadfile_.UPLOADFILE_.FILETYPE, values);
    }

    /**
     * Fetch records that have <code>accountId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Uploadfile_> fetchByAccountid(Long... values) {
        return fetch(Uploadfile_.UPLOADFILE_.ACCOUNTID, values);
    }

    /**
     * Fetch records that have <code>accountType IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Uploadfile_> fetchByAccounttype(Integer... values) {
        return fetch(Uploadfile_.UPLOADFILE_.ACCOUNTTYPE, values);
    }

    /**
     * Fetch records that have <code>fileName IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Uploadfile_> fetchByFilename(String... values) {
        return fetch(Uploadfile_.UPLOADFILE_.FILENAME, values);
    }

    /**
     * Fetch records that have <code>fileURL IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Uploadfile_> fetchByFileurl(String... values) {
        return fetch(Uploadfile_.UPLOADFILE_.FILEURL, values);
    }

    /**
     * Fetch records that have <code>deleteStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Uploadfile_> fetchByDeletestatus(Integer... values) {
        return fetch(Uploadfile_.UPLOADFILE_.DELETESTATUS, values);
    }

    /**
     * Fetch records that have <code>createdTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Uploadfile_> fetchByCreatedtime(Timestamp... values) {
        return fetch(Uploadfile_.UPLOADFILE_.CREATEDTIME, values);
    }

    /**
     * Fetch records that have <code>lastModifiedTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Uploadfile_> fetchByLastmodifiedtime(Timestamp... values) {
        return fetch(Uploadfile_.UPLOADFILE_.LASTMODIFIEDTIME, values);
    }
}
