/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.daos;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.User_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.User_Record;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User_Dao extends DAOImpl<User_Record, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.User_, Long> {

    /**
     * Create a new User_Dao without any configuration
     */
    public User_Dao() {
        super(User_.USER_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.User_.class);
    }

    /**
     * Create a new User_Dao with an attached configuration
     */
    public User_Dao(Configuration configuration) {
        super(User_.USER_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.User_.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.User_ object) {
        return object.getUserid();
    }

    /**
     * Fetch records that have <code>userId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.User_> fetchByUserid(Long... values) {
        return fetch(User_.USER_.USERID, values);
    }

    /**
     * Fetch a unique record that has <code>userId = value</code>
     */
    public cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.User_ fetchOneByUserid(Long value) {
        return fetchOne(User_.USER_.USERID, value);
    }

    /**
     * Fetch records that have <code>userName IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.User_> fetchByUsername(String... values) {
        return fetch(User_.USER_.USERNAME, values);
    }

    /**
     * Fetch records that have <code>cellphone IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.User_> fetchByCellphone(String... values) {
        return fetch(User_.USER_.CELLPHONE, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.User_> fetchByEmail(String... values) {
        return fetch(User_.USER_.EMAIL, values);
    }

    /**
     * Fetch records that have <code>createdTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.User_> fetchByCreatedtime(Timestamp... values) {
        return fetch(User_.USER_.CREATEDTIME, values);
    }

    /**
     * Fetch records that have <code>deleteStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.User_> fetchByDeletestatus(Integer... values) {
        return fetch(User_.USER_.DELETESTATUS, values);
    }

    /**
     * Fetch records that have <code>lastModifiedUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.User_> fetchByLastmodifieduserid(Long... values) {
        return fetch(User_.USER_.LASTMODIFIEDUSERID, values);
    }

    /**
     * Fetch records that have <code>lastModifiedTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.User_> fetchByLastmodifiedtime(Timestamp... values) {
        return fetch(User_.USER_.LASTMODIFIEDTIME, values);
    }

    /**
     * Fetch records that have <code>createdUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.User_> fetchByCreateduserid(Long... values) {
        return fetch(User_.USER_.CREATEDUSERID, values);
    }
}
