/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.daos;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Userlogin_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.Userlogin_Record;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 用户登录表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userlogin_Dao extends DAOImpl<Userlogin_Record, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Userlogin_, Long> {

    /**
     * Create a new Userlogin_Dao without any configuration
     */
    public Userlogin_Dao() {
        super(Userlogin_.USERLOGIN_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Userlogin_.class);
    }

    /**
     * Create a new Userlogin_Dao with an attached configuration
     */
    public Userlogin_Dao(Configuration configuration) {
        super(Userlogin_.USERLOGIN_, cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Userlogin_.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Userlogin_ object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Userlogin_> fetchById(Long... values) {
        return fetch(Userlogin_.USERLOGIN_.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Userlogin_ fetchOneById(Long value) {
        return fetchOne(Userlogin_.USERLOGIN_.ID, value);
    }

    /**
     * Fetch records that have <code>userId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Userlogin_> fetchByUserid(Long... values) {
        return fetch(Userlogin_.USERLOGIN_.USERID, values);
    }

    /**
     * Fetch records that have <code>loginName IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Userlogin_> fetchByLoginname(String... values) {
        return fetch(Userlogin_.USERLOGIN_.LOGINNAME, values);
    }

    /**
     * Fetch records that have <code>loginNameType IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Userlogin_> fetchByLoginnametype(Integer... values) {
        return fetch(Userlogin_.USERLOGIN_.LOGINNAMETYPE, values);
    }

    /**
     * Fetch records that have <code>deleteStatus IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Userlogin_> fetchByDeletestatus(Integer... values) {
        return fetch(Userlogin_.USERLOGIN_.DELETESTATUS, values);
    }

    /**
     * Fetch records that have <code>createdTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Userlogin_> fetchByCreatedtime(Timestamp... values) {
        return fetch(Userlogin_.USERLOGIN_.CREATEDTIME, values);
    }

    /**
     * Fetch records that have <code>createdUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Userlogin_> fetchByCreateduserid(Long... values) {
        return fetch(Userlogin_.USERLOGIN_.CREATEDUSERID, values);
    }

    /**
     * Fetch records that have <code>lastModifiedUserId IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Userlogin_> fetchByLastmodifieduserid(Long... values) {
        return fetch(Userlogin_.USERLOGIN_.LASTMODIFIEDUSERID, values);
    }

    /**
     * Fetch records that have <code>lastModifiedTime IN (values)</code>
     */
    public List<cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos.Userlogin_> fetchByLastmodifiedtime(Timestamp... values) {
        return fetch(Userlogin_.USERLOGIN_.LASTMODIFIEDTIME, values);
    }
}
