/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account_ implements Serializable {

    private static final long serialVersionUID = 159809807;

    private Long      accountid;
    private Integer   accounttype;
    private String    nickname;
    private Integer   accountstatus;
    private Integer   approvalstatus;
    private String    memo;
    private Long      audituserid;
    private String    auditmsg;
    private Timestamp auditedtime;
    private Long      createduserid;
    private Timestamp createdtime;
    private Integer   deletestatus;
    private Long      lastmodifieduserid;
    private Timestamp lastmodifiedtime;

    public Account_() {}

    public Account_(Account_ value) {
        this.accountid = value.accountid;
        this.accounttype = value.accounttype;
        this.nickname = value.nickname;
        this.accountstatus = value.accountstatus;
        this.approvalstatus = value.approvalstatus;
        this.memo = value.memo;
        this.audituserid = value.audituserid;
        this.auditmsg = value.auditmsg;
        this.auditedtime = value.auditedtime;
        this.createduserid = value.createduserid;
        this.createdtime = value.createdtime;
        this.deletestatus = value.deletestatus;
        this.lastmodifieduserid = value.lastmodifieduserid;
        this.lastmodifiedtime = value.lastmodifiedtime;
    }

    public Account_(
        Long      accountid,
        Integer   accounttype,
        String    nickname,
        Integer   accountstatus,
        Integer   approvalstatus,
        String    memo,
        Long      audituserid,
        String    auditmsg,
        Timestamp auditedtime,
        Long      createduserid,
        Timestamp createdtime,
        Integer   deletestatus,
        Long      lastmodifieduserid,
        Timestamp lastmodifiedtime
    ) {
        this.accountid = accountid;
        this.accounttype = accounttype;
        this.nickname = nickname;
        this.accountstatus = accountstatus;
        this.approvalstatus = approvalstatus;
        this.memo = memo;
        this.audituserid = audituserid;
        this.auditmsg = auditmsg;
        this.auditedtime = auditedtime;
        this.createduserid = createduserid;
        this.createdtime = createdtime;
        this.deletestatus = deletestatus;
        this.lastmodifieduserid = lastmodifieduserid;
        this.lastmodifiedtime = lastmodifiedtime;
    }

    public Long getAccountid() {
        return this.accountid;
    }

    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    public Integer getAccounttype() {
        return this.accounttype;
    }

    public void setAccounttype(Integer accounttype) {
        this.accounttype = accounttype;
    }

    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Integer getAccountstatus() {
        return this.accountstatus;
    }

    public void setAccountstatus(Integer accountstatus) {
        this.accountstatus = accountstatus;
    }

    public Integer getApprovalstatus() {
        return this.approvalstatus;
    }

    public void setApprovalstatus(Integer approvalstatus) {
        this.approvalstatus = approvalstatus;
    }

    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Long getAudituserid() {
        return this.audituserid;
    }

    public void setAudituserid(Long audituserid) {
        this.audituserid = audituserid;
    }

    public String getAuditmsg() {
        return this.auditmsg;
    }

    public void setAuditmsg(String auditmsg) {
        this.auditmsg = auditmsg;
    }

    public Timestamp getAuditedtime() {
        return this.auditedtime;
    }

    public void setAuditedtime(Timestamp auditedtime) {
        this.auditedtime = auditedtime;
    }

    public Long getCreateduserid() {
        return this.createduserid;
    }

    public void setCreateduserid(Long createduserid) {
        this.createduserid = createduserid;
    }

    public Timestamp getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Timestamp createdtime) {
        this.createdtime = createdtime;
    }

    public Integer getDeletestatus() {
        return this.deletestatus;
    }

    public void setDeletestatus(Integer deletestatus) {
        this.deletestatus = deletestatus;
    }

    public Long getLastmodifieduserid() {
        return this.lastmodifieduserid;
    }

    public void setLastmodifieduserid(Long lastmodifieduserid) {
        this.lastmodifieduserid = lastmodifieduserid;
    }

    public Timestamp getLastmodifiedtime() {
        return this.lastmodifiedtime;
    }

    public void setLastmodifiedtime(Timestamp lastmodifiedtime) {
        this.lastmodifiedtime = lastmodifiedtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account_ (");

        sb.append(accountid);
        sb.append(", ").append(accounttype);
        sb.append(", ").append(nickname);
        sb.append(", ").append(accountstatus);
        sb.append(", ").append(approvalstatus);
        sb.append(", ").append(memo);
        sb.append(", ").append(audituserid);
        sb.append(", ").append(auditmsg);
        sb.append(", ").append(auditedtime);
        sb.append(", ").append(createduserid);
        sb.append(", ").append(createdtime);
        sb.append(", ").append(deletestatus);
        sb.append(", ").append(lastmodifieduserid);
        sb.append(", ").append(lastmodifiedtime);

        sb.append(")");
        return sb.toString();
    }
}
