/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 用于存储账号对应用户和角色信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Accountuserrole_ implements Serializable {

    private static final long serialVersionUID = 1699765193;

    private Long      accountroleid;
    private Integer   accounttype;
    private Long      userid;
    private Long      accountid;
    private Integer   role;
    private Integer   deletestatus;
    private Timestamp createdtime;
    private Long      createduserid;
    private Long      lastmodifieduserid;
    private Timestamp lastmodifiedtime;

    public Accountuserrole_() {}

    public Accountuserrole_(Accountuserrole_ value) {
        this.accountroleid = value.accountroleid;
        this.accounttype = value.accounttype;
        this.userid = value.userid;
        this.accountid = value.accountid;
        this.role = value.role;
        this.deletestatus = value.deletestatus;
        this.createdtime = value.createdtime;
        this.createduserid = value.createduserid;
        this.lastmodifieduserid = value.lastmodifieduserid;
        this.lastmodifiedtime = value.lastmodifiedtime;
    }

    public Accountuserrole_(
        Long      accountroleid,
        Integer   accounttype,
        Long      userid,
        Long      accountid,
        Integer   role,
        Integer   deletestatus,
        Timestamp createdtime,
        Long      createduserid,
        Long      lastmodifieduserid,
        Timestamp lastmodifiedtime
    ) {
        this.accountroleid = accountroleid;
        this.accounttype = accounttype;
        this.userid = userid;
        this.accountid = accountid;
        this.role = role;
        this.deletestatus = deletestatus;
        this.createdtime = createdtime;
        this.createduserid = createduserid;
        this.lastmodifieduserid = lastmodifieduserid;
        this.lastmodifiedtime = lastmodifiedtime;
    }

    public Long getAccountroleid() {
        return this.accountroleid;
    }

    public void setAccountroleid(Long accountroleid) {
        this.accountroleid = accountroleid;
    }

    public Integer getAccounttype() {
        return this.accounttype;
    }

    public void setAccounttype(Integer accounttype) {
        this.accounttype = accounttype;
    }

    public Long getUserid() {
        return this.userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }

    public Long getAccountid() {
        return this.accountid;
    }

    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    public Integer getRole() {
        return this.role;
    }

    public void setRole(Integer role) {
        this.role = role;
    }

    public Integer getDeletestatus() {
        return this.deletestatus;
    }

    public void setDeletestatus(Integer deletestatus) {
        this.deletestatus = deletestatus;
    }

    public Timestamp getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Timestamp createdtime) {
        this.createdtime = createdtime;
    }

    public Long getCreateduserid() {
        return this.createduserid;
    }

    public void setCreateduserid(Long createduserid) {
        this.createduserid = createduserid;
    }

    public Long getLastmodifieduserid() {
        return this.lastmodifieduserid;
    }

    public void setLastmodifieduserid(Long lastmodifieduserid) {
        this.lastmodifieduserid = lastmodifieduserid;
    }

    public Timestamp getLastmodifiedtime() {
        return this.lastmodifiedtime;
    }

    public void setLastmodifiedtime(Timestamp lastmodifiedtime) {
        this.lastmodifiedtime = lastmodifiedtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Accountuserrole_ (");

        sb.append(accountroleid);
        sb.append(", ").append(accounttype);
        sb.append(", ").append(userid);
        sb.append(", ").append(accountid);
        sb.append(", ").append(role);
        sb.append(", ").append(deletestatus);
        sb.append(", ").append(createdtime);
        sb.append(", ").append(createduserid);
        sb.append(", ").append(lastmodifieduserid);
        sb.append(", ").append(lastmodifiedtime);

        sb.append(")");
        return sb.toString();
    }
}
