/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 学院信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Department_ implements Serializable {

    private static final long serialVersionUID = -521022022;

    private Integer   departmentid;
    private Integer   collegeid;
    private String    name;
    private Timestamp createdtime;
    private Integer   deletestatus;
    private Timestamp lastmodifiedtime;

    public Department_() {}

    public Department_(Department_ value) {
        this.departmentid = value.departmentid;
        this.collegeid = value.collegeid;
        this.name = value.name;
        this.createdtime = value.createdtime;
        this.deletestatus = value.deletestatus;
        this.lastmodifiedtime = value.lastmodifiedtime;
    }

    public Department_(
        Integer   departmentid,
        Integer   collegeid,
        String    name,
        Timestamp createdtime,
        Integer   deletestatus,
        Timestamp lastmodifiedtime
    ) {
        this.departmentid = departmentid;
        this.collegeid = collegeid;
        this.name = name;
        this.createdtime = createdtime;
        this.deletestatus = deletestatus;
        this.lastmodifiedtime = lastmodifiedtime;
    }

    public Integer getDepartmentid() {
        return this.departmentid;
    }

    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    public Integer getCollegeid() {
        return this.collegeid;
    }

    public void setCollegeid(Integer collegeid) {
        this.collegeid = collegeid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Timestamp getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Timestamp createdtime) {
        this.createdtime = createdtime;
    }

    public Integer getDeletestatus() {
        return this.deletestatus;
    }

    public void setDeletestatus(Integer deletestatus) {
        this.deletestatus = deletestatus;
    }

    public Timestamp getLastmodifiedtime() {
        return this.lastmodifiedtime;
    }

    public void setLastmodifiedtime(Timestamp lastmodifiedtime) {
        this.lastmodifiedtime = lastmodifiedtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Department_ (");

        sb.append(departmentid);
        sb.append(", ").append(collegeid);
        sb.append(", ").append(name);
        sb.append(", ").append(createdtime);
        sb.append(", ").append(deletestatus);
        sb.append(", ").append(lastmodifiedtime);

        sb.append(")");
        return sb.toString();
    }
}
