/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 消息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Message_ implements Serializable {

    private static final long serialVersionUID = 970754649;

    private Long      id;
    private Long      accountid;
    private Integer   type;
    private String    content;
    private Integer   status;
    private Timestamp createdtime;
    private Integer   deletestatus;
    private Timestamp lastmodifiedtime;

    public Message_() {}

    public Message_(Message_ value) {
        this.id = value.id;
        this.accountid = value.accountid;
        this.type = value.type;
        this.content = value.content;
        this.status = value.status;
        this.createdtime = value.createdtime;
        this.deletestatus = value.deletestatus;
        this.lastmodifiedtime = value.lastmodifiedtime;
    }

    public Message_(
        Long      id,
        Long      accountid,
        Integer   type,
        String    content,
        Integer   status,
        Timestamp createdtime,
        Integer   deletestatus,
        Timestamp lastmodifiedtime
    ) {
        this.id = id;
        this.accountid = accountid;
        this.type = type;
        this.content = content;
        this.status = status;
        this.createdtime = createdtime;
        this.deletestatus = deletestatus;
        this.lastmodifiedtime = lastmodifiedtime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccountid() {
        return this.accountid;
    }

    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Timestamp getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Timestamp createdtime) {
        this.createdtime = createdtime;
    }

    public Integer getDeletestatus() {
        return this.deletestatus;
    }

    public void setDeletestatus(Integer deletestatus) {
        this.deletestatus = deletestatus;
    }

    public Timestamp getLastmodifiedtime() {
        return this.lastmodifiedtime;
    }

    public void setLastmodifiedtime(Timestamp lastmodifiedtime) {
        this.lastmodifiedtime = lastmodifiedtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Message_ (");

        sb.append(id);
        sb.append(", ").append(accountid);
        sb.append(", ").append(type);
        sb.append(", ").append(content);
        sb.append(", ").append(status);
        sb.append(", ").append(createdtime);
        sb.append(", ").append(deletestatus);
        sb.append(", ").append(lastmodifiedtime);

        sb.append(")");
        return sb.toString();
    }
}
