/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Normalaccount_ implements Serializable {

    private static final long serialVersionUID = 1748720256;

    private Long      accountid;
    private Integer   accounttype;
    private Integer   collegeid;
    private Integer   departmentid;
    private String    major;
    private String    stuid;
    private Long      createduserid;
    private Timestamp createdtime;
    private Integer   deletestatus;
    private Long      lastmodifieduserid;
    private Timestamp lastmodifiedtime;

    public Normalaccount_() {}

    public Normalaccount_(Normalaccount_ value) {
        this.accountid = value.accountid;
        this.accounttype = value.accounttype;
        this.collegeid = value.collegeid;
        this.departmentid = value.departmentid;
        this.major = value.major;
        this.stuid = value.stuid;
        this.createduserid = value.createduserid;
        this.createdtime = value.createdtime;
        this.deletestatus = value.deletestatus;
        this.lastmodifieduserid = value.lastmodifieduserid;
        this.lastmodifiedtime = value.lastmodifiedtime;
    }

    public Normalaccount_(
        Long      accountid,
        Integer   accounttype,
        Integer   collegeid,
        Integer   departmentid,
        String    major,
        String    stuid,
        Long      createduserid,
        Timestamp createdtime,
        Integer   deletestatus,
        Long      lastmodifieduserid,
        Timestamp lastmodifiedtime
    ) {
        this.accountid = accountid;
        this.accounttype = accounttype;
        this.collegeid = collegeid;
        this.departmentid = departmentid;
        this.major = major;
        this.stuid = stuid;
        this.createduserid = createduserid;
        this.createdtime = createdtime;
        this.deletestatus = deletestatus;
        this.lastmodifieduserid = lastmodifieduserid;
        this.lastmodifiedtime = lastmodifiedtime;
    }

    public Long getAccountid() {
        return this.accountid;
    }

    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    public Integer getAccounttype() {
        return this.accounttype;
    }

    public void setAccounttype(Integer accounttype) {
        this.accounttype = accounttype;
    }

    public Integer getCollegeid() {
        return this.collegeid;
    }

    public void setCollegeid(Integer collegeid) {
        this.collegeid = collegeid;
    }

    public Integer getDepartmentid() {
        return this.departmentid;
    }

    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    public String getMajor() {
        return this.major;
    }

    public void setMajor(String major) {
        this.major = major;
    }

    public String getStuid() {
        return this.stuid;
    }

    public void setStuid(String stuid) {
        this.stuid = stuid;
    }

    public Long getCreateduserid() {
        return this.createduserid;
    }

    public void setCreateduserid(Long createduserid) {
        this.createduserid = createduserid;
    }

    public Timestamp getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Timestamp createdtime) {
        this.createdtime = createdtime;
    }

    public Integer getDeletestatus() {
        return this.deletestatus;
    }

    public void setDeletestatus(Integer deletestatus) {
        this.deletestatus = deletestatus;
    }

    public Long getLastmodifieduserid() {
        return this.lastmodifieduserid;
    }

    public void setLastmodifieduserid(Long lastmodifieduserid) {
        this.lastmodifieduserid = lastmodifieduserid;
    }

    public Timestamp getLastmodifiedtime() {
        return this.lastmodifiedtime;
    }

    public void setLastmodifiedtime(Timestamp lastmodifiedtime) {
        this.lastmodifiedtime = lastmodifiedtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Normalaccount_ (");

        sb.append(accountid);
        sb.append(", ").append(accounttype);
        sb.append(", ").append(collegeid);
        sb.append(", ").append(departmentid);
        sb.append(", ").append(major);
        sb.append(", ").append(stuid);
        sb.append(", ").append(createduserid);
        sb.append(", ").append(createdtime);
        sb.append(", ").append(deletestatus);
        sb.append(", ").append(lastmodifieduserid);
        sb.append(", ").append(lastmodifiedtime);

        sb.append(")");
        return sb.toString();
    }
}
