/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 公告
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notification_ implements Serializable {

    private static final long serialVersionUID = -1617519170;

    private Integer   noticeid;
    private Integer   type;
    private String    frontimg;
    private Integer   status;
    private String    content;
    private Integer   deletestatus;
    private Timestamp createdtime;
    private Timestamp lastmodifiedtime;

    public Notification_() {}

    public Notification_(Notification_ value) {
        this.noticeid = value.noticeid;
        this.type = value.type;
        this.frontimg = value.frontimg;
        this.status = value.status;
        this.content = value.content;
        this.deletestatus = value.deletestatus;
        this.createdtime = value.createdtime;
        this.lastmodifiedtime = value.lastmodifiedtime;
    }

    public Notification_(
        Integer   noticeid,
        Integer   type,
        String    frontimg,
        Integer   status,
        String    content,
        Integer   deletestatus,
        Timestamp createdtime,
        Timestamp lastmodifiedtime
    ) {
        this.noticeid = noticeid;
        this.type = type;
        this.frontimg = frontimg;
        this.status = status;
        this.content = content;
        this.deletestatus = deletestatus;
        this.createdtime = createdtime;
        this.lastmodifiedtime = lastmodifiedtime;
    }

    public Integer getNoticeid() {
        return this.noticeid;
    }

    public void setNoticeid(Integer noticeid) {
        this.noticeid = noticeid;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getFrontimg() {
        return this.frontimg;
    }

    public void setFrontimg(String frontimg) {
        this.frontimg = frontimg;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getDeletestatus() {
        return this.deletestatus;
    }

    public void setDeletestatus(Integer deletestatus) {
        this.deletestatus = deletestatus;
    }

    public Timestamp getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Timestamp createdtime) {
        this.createdtime = createdtime;
    }

    public Timestamp getLastmodifiedtime() {
        return this.lastmodifiedtime;
    }

    public void setLastmodifiedtime(Timestamp lastmodifiedtime) {
        this.lastmodifiedtime = lastmodifiedtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Notification_ (");

        sb.append(noticeid);
        sb.append(", ").append(type);
        sb.append(", ").append(frontimg);
        sb.append(", ").append(status);
        sb.append(", ").append(content);
        sb.append(", ").append(deletestatus);
        sb.append(", ").append(createdtime);
        sb.append(", ").append(lastmodifiedtime);

        sb.append(")");
        return sb.toString();
    }
}
