/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 用于存储openId对应qq关联关系
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Openidqqidx_ implements Serializable {

    private static final long serialVersionUID = 1993932274;

    private String  openid;
    private String  qqnumber;
    private Integer deletestatus;

    public Openidqqidx_() {}

    public Openidqqidx_(Openidqqidx_ value) {
        this.openid = value.openid;
        this.qqnumber = value.qqnumber;
        this.deletestatus = value.deletestatus;
    }

    public Openidqqidx_(
        String  openid,
        String  qqnumber,
        Integer deletestatus
    ) {
        this.openid = openid;
        this.qqnumber = qqnumber;
        this.deletestatus = deletestatus;
    }

    public String getOpenid() {
        return this.openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    public String getQqnumber() {
        return this.qqnumber;
    }

    public void setQqnumber(String qqnumber) {
        this.qqnumber = qqnumber;
    }

    public Integer getDeletestatus() {
        return this.deletestatus;
    }

    public void setDeletestatus(Integer deletestatus) {
        this.deletestatus = deletestatus;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Openidqqidx_ (");

        sb.append(openid);
        sb.append(", ").append(qqnumber);
        sb.append(", ").append(deletestatus);

        sb.append(")");
        return sb.toString();
    }
}
