/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 组织
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organize_ implements Serializable {

    private static final long serialVersionUID = 1019928446;

    private Long      organizeid;
    private Long      competitionid;
    private Long      srcaccountid;
    private Long      createduserid;
    private Timestamp createdtime;
    private Integer   deletestatus;
    private Long      lastmodifieduserid;
    private Timestamp lastmodifiedtime;

    public Organize_() {}

    public Organize_(Organize_ value) {
        this.organizeid = value.organizeid;
        this.competitionid = value.competitionid;
        this.srcaccountid = value.srcaccountid;
        this.createduserid = value.createduserid;
        this.createdtime = value.createdtime;
        this.deletestatus = value.deletestatus;
        this.lastmodifieduserid = value.lastmodifieduserid;
        this.lastmodifiedtime = value.lastmodifiedtime;
    }

    public Organize_(
        Long      organizeid,
        Long      competitionid,
        Long      srcaccountid,
        Long      createduserid,
        Timestamp createdtime,
        Integer   deletestatus,
        Long      lastmodifieduserid,
        Timestamp lastmodifiedtime
    ) {
        this.organizeid = organizeid;
        this.competitionid = competitionid;
        this.srcaccountid = srcaccountid;
        this.createduserid = createduserid;
        this.createdtime = createdtime;
        this.deletestatus = deletestatus;
        this.lastmodifieduserid = lastmodifieduserid;
        this.lastmodifiedtime = lastmodifiedtime;
    }

    public Long getOrganizeid() {
        return this.organizeid;
    }

    public void setOrganizeid(Long organizeid) {
        this.organizeid = organizeid;
    }

    public Long getCompetitionid() {
        return this.competitionid;
    }

    public void setCompetitionid(Long competitionid) {
        this.competitionid = competitionid;
    }

    public Long getSrcaccountid() {
        return this.srcaccountid;
    }

    public void setSrcaccountid(Long srcaccountid) {
        this.srcaccountid = srcaccountid;
    }

    public Long getCreateduserid() {
        return this.createduserid;
    }

    public void setCreateduserid(Long createduserid) {
        this.createduserid = createduserid;
    }

    public Timestamp getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Timestamp createdtime) {
        this.createdtime = createdtime;
    }

    public Integer getDeletestatus() {
        return this.deletestatus;
    }

    public void setDeletestatus(Integer deletestatus) {
        this.deletestatus = deletestatus;
    }

    public Long getLastmodifieduserid() {
        return this.lastmodifieduserid;
    }

    public void setLastmodifieduserid(Long lastmodifieduserid) {
        this.lastmodifieduserid = lastmodifieduserid;
    }

    public Timestamp getLastmodifiedtime() {
        return this.lastmodifiedtime;
    }

    public void setLastmodifiedtime(Timestamp lastmodifiedtime) {
        this.lastmodifiedtime = lastmodifiedtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Organize_ (");

        sb.append(organizeid);
        sb.append(", ").append(competitionid);
        sb.append(", ").append(srcaccountid);
        sb.append(", ").append(createduserid);
        sb.append(", ").append(createdtime);
        sb.append(", ").append(deletestatus);
        sb.append(", ").append(lastmodifieduserid);
        sb.append(", ").append(lastmodifiedtime);

        sb.append(")");
        return sb.toString();
    }
}
