/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * OrganizeAccount关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organizeaccountrelation_ implements Serializable {

    private static final long serialVersionUID = -1904643065;

    private Long      id;
    private Long      organizeid;
    private Long      accountid;
    private Integer   accounttype;
    private Integer   isowneraccount;
    private Long      createduserid;
    private Timestamp createdtime;
    private Integer   deletestatus;
    private Long      lastmodifieduserid;
    private Timestamp lastmodifiedtime;

    public Organizeaccountrelation_() {}

    public Organizeaccountrelation_(Organizeaccountrelation_ value) {
        this.id = value.id;
        this.organizeid = value.organizeid;
        this.accountid = value.accountid;
        this.accounttype = value.accounttype;
        this.isowneraccount = value.isowneraccount;
        this.createduserid = value.createduserid;
        this.createdtime = value.createdtime;
        this.deletestatus = value.deletestatus;
        this.lastmodifieduserid = value.lastmodifieduserid;
        this.lastmodifiedtime = value.lastmodifiedtime;
    }

    public Organizeaccountrelation_(
        Long      id,
        Long      organizeid,
        Long      accountid,
        Integer   accounttype,
        Integer   isowneraccount,
        Long      createduserid,
        Timestamp createdtime,
        Integer   deletestatus,
        Long      lastmodifieduserid,
        Timestamp lastmodifiedtime
    ) {
        this.id = id;
        this.organizeid = organizeid;
        this.accountid = accountid;
        this.accounttype = accounttype;
        this.isowneraccount = isowneraccount;
        this.createduserid = createduserid;
        this.createdtime = createdtime;
        this.deletestatus = deletestatus;
        this.lastmodifieduserid = lastmodifieduserid;
        this.lastmodifiedtime = lastmodifiedtime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getOrganizeid() {
        return this.organizeid;
    }

    public void setOrganizeid(Long organizeid) {
        this.organizeid = organizeid;
    }

    public Long getAccountid() {
        return this.accountid;
    }

    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    public Integer getAccounttype() {
        return this.accounttype;
    }

    public void setAccounttype(Integer accounttype) {
        this.accounttype = accounttype;
    }

    public Integer getIsowneraccount() {
        return this.isowneraccount;
    }

    public void setIsowneraccount(Integer isowneraccount) {
        this.isowneraccount = isowneraccount;
    }

    public Long getCreateduserid() {
        return this.createduserid;
    }

    public void setCreateduserid(Long createduserid) {
        this.createduserid = createduserid;
    }

    public Timestamp getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Timestamp createdtime) {
        this.createdtime = createdtime;
    }

    public Integer getDeletestatus() {
        return this.deletestatus;
    }

    public void setDeletestatus(Integer deletestatus) {
        this.deletestatus = deletestatus;
    }

    public Long getLastmodifieduserid() {
        return this.lastmodifieduserid;
    }

    public void setLastmodifieduserid(Long lastmodifieduserid) {
        this.lastmodifieduserid = lastmodifieduserid;
    }

    public Timestamp getLastmodifiedtime() {
        return this.lastmodifiedtime;
    }

    public void setLastmodifiedtime(Timestamp lastmodifiedtime) {
        this.lastmodifiedtime = lastmodifiedtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Organizeaccountrelation_ (");

        sb.append(id);
        sb.append(", ").append(organizeid);
        sb.append(", ").append(accountid);
        sb.append(", ").append(accounttype);
        sb.append(", ").append(isowneraccount);
        sb.append(", ").append(createduserid);
        sb.append(", ").append(createdtime);
        sb.append(", ").append(deletestatus);
        sb.append(", ").append(lastmodifieduserid);
        sb.append(", ").append(lastmodifiedtime);

        sb.append(")");
        return sb.toString();
    }
}
