/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Account_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Accountuserrole_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Openidqqidx_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Openidwxidx_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.User_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Userlogin_;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dfu_ extends SchemaImpl {

    private static final long serialVersionUID = 1486391893;

    /**
     * The reference instance of <code>DFU_</code>
     */
    public static final Dfu_ DFU_ = new Dfu_();

    /**
     * 用于存储账号对应用户和角色信息
     */
    public final Accountuserrole_ ACCOUNTUSERROLE_ = Accountuserrole_.ACCOUNTUSERROLE_;

    /**
     * The table <code>DFU_.Account_</code>.
     */
    public final Account_ ACCOUNT_ = Account_.ACCOUNT_;

    /**
     * 用于存储openId对应qq关联关系
     */
    public final Openidqqidx_ OPENIDQQIDX_ = Openidqqidx_.OPENIDQQIDX_;

    /**
     * 用于存储openId对应wx关联关系
     */
    public final Openidwxidx_ OPENIDWXIDX_ = Openidwxidx_.OPENIDWXIDX_;

    /**
     * 用户登录表
     */
    public final Userlogin_ USERLOGIN_ = Userlogin_.USERLOGIN_;

    /**
     * The table <code>DFU_.User_</code>.
     */
    public final User_ USER_ = User_.USER_;

    /**
     * No further instances allowed
     */
    private Dfu_() {
        super("DFU_", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Accountuserrole_.ACCOUNTUSERROLE_,
            Account_.ACCOUNT_,
            Openidqqidx_.OPENIDQQIDX_,
            Openidwxidx_.OPENIDWXIDX_,
            Userlogin_.USERLOGIN_,
            User_.USER_);
    }
}
