/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables;


import cn.gatesma.desirefu.domain.db.generate.DFU_.Dfu_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.Indexes;
import cn.gatesma.desirefu.domain.db.generate.DFU_.Keys;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.Competitionvisible_Record;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 高校可见比赛表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Competitionvisible_ extends TableImpl<Competitionvisible_Record> {

    private static final long serialVersionUID = 197495782;

    /**
     * The reference instance of <code>DFU_.CompetitionVisible_</code>
     */
    public static final Competitionvisible_ COMPETITIONVISIBLE_ = new Competitionvisible_();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Competitionvisible_Record> getRecordType() {
        return Competitionvisible_Record.class;
    }

    /**
     * The column <code>DFU_.CompetitionVisible_.collegeId</code>. 高校ID
     */
    public final TableField<Competitionvisible_Record, Integer> COLLEGEID = createField("collegeId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "高校ID");

    /**
     * The column <code>DFU_.CompetitionVisible_.competitionId</code>. 帐号ID
     */
    public final TableField<Competitionvisible_Record, Long> COMPETITIONID = createField("competitionId", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "帐号ID");

    /**
     * The column <code>DFU_.CompetitionVisible_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public final TableField<Competitionvisible_Record, Integer> DELETESTATUS = createField("deleteStatus", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "删除状态，0-正常，1-删除");

    /**
     * The column <code>DFU_.CompetitionVisible_.createdTime</code>. 创建时间
     */
    public final TableField<Competitionvisible_Record, Timestamp> CREATEDTIME = createField("createdTime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>DFU_.CompetitionVisible_.lastModifiedTime</code>. lastModifiedTime
     */
    public final TableField<Competitionvisible_Record, Timestamp> LASTMODIFIEDTIME = createField("lastModifiedTime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "lastModifiedTime");

    /**
     * Create a <code>DFU_.CompetitionVisible_</code> table reference
     */
    public Competitionvisible_() {
        this(DSL.name("CompetitionVisible_"), null);
    }

    /**
     * Create an aliased <code>DFU_.CompetitionVisible_</code> table reference
     */
    public Competitionvisible_(String alias) {
        this(DSL.name(alias), COMPETITIONVISIBLE_);
    }

    /**
     * Create an aliased <code>DFU_.CompetitionVisible_</code> table reference
     */
    public Competitionvisible_(Name alias) {
        this(alias, COMPETITIONVISIBLE_);
    }

    private Competitionvisible_(Name alias, Table<Competitionvisible_Record> aliased) {
        this(alias, aliased, null);
    }

    private Competitionvisible_(Name alias, Table<Competitionvisible_Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "高校可见比赛表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dfu_.DFU_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COMPETITIONVISIBLE__PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Competitionvisible_Record> getPrimaryKey() {
        return Keys.KEY_COMPETITIONVISIBLE__PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Competitionvisible_Record>> getKeys() {
        return Arrays.<UniqueKey<Competitionvisible_Record>>asList(Keys.KEY_COMPETITIONVISIBLE__PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competitionvisible_ as(String alias) {
        return new Competitionvisible_(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competitionvisible_ as(Name alias) {
        return new Competitionvisible_(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Competitionvisible_ rename(String name) {
        return new Competitionvisible_(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Competitionvisible_ rename(Name name) {
        return new Competitionvisible_(name, null);
    }
}
