/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables;


import cn.gatesma.desirefu.domain.db.generate.DFU_.Dfu_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.Indexes;
import cn.gatesma.desirefu.domain.db.generate.DFU_.Keys;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.Organize_Record;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 组织
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organize_ extends TableImpl<Organize_Record> {

    private static final long serialVersionUID = 628897483;

    /**
     * The reference instance of <code>DFU_.Organize_</code>
     */
    public static final Organize_ ORGANIZE_ = new Organize_();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Organize_Record> getRecordType() {
        return Organize_Record.class;
    }

    /**
     * The column <code>DFU_.Organize_.organizeId</code>. 圈子Id, 等于account表里的accountId
     */
    public final TableField<Organize_Record, Long> ORGANIZEID = createField("organizeId", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "圈子Id, 等于account表里的accountId");

    /**
     * The column <code>DFU_.Organize_.competitionId</code>. 比赛ID
     */
    public final TableField<Organize_Record, Long> COMPETITIONID = createField("competitionId", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "比赛ID");

    /**
     * The column <code>DFU_.Organize_.srcAccountId</code>. 队长账号Id
     */
    public final TableField<Organize_Record, Long> SRCACCOUNTID = createField("srcAccountId", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "队长账号Id");

    /**
     * The column <code>DFU_.Organize_.createdUserId</code>. 创建人userId
     */
    public final TableField<Organize_Record, Long> CREATEDUSERID = createField("createdUserId", org.jooq.impl.SQLDataType.BIGINT, this, "创建人userId");

    /**
     * The column <code>DFU_.Organize_.createdTime</code>. 创建时间
     */
    public final TableField<Organize_Record, Timestamp> CREATEDTIME = createField("createdTime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "创建时间");

    /**
     * The column <code>DFU_.Organize_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public final TableField<Organize_Record, Integer> DELETESTATUS = createField("deleteStatus", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "删除状态，0-正常，1-删除");

    /**
     * The column <code>DFU_.Organize_.lastModifiedUserId</code>. 最后修改人userId
     */
    public final TableField<Organize_Record, Long> LASTMODIFIEDUSERID = createField("lastModifiedUserId", org.jooq.impl.SQLDataType.BIGINT, this, "最后修改人userId");

    /**
     * The column <code>DFU_.Organize_.lastModifiedTime</code>. lastModifiedTime
     */
    public final TableField<Organize_Record, Timestamp> LASTMODIFIEDTIME = createField("lastModifiedTime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "lastModifiedTime");

    /**
     * Create a <code>DFU_.Organize_</code> table reference
     */
    public Organize_() {
        this(DSL.name("Organize_"), null);
    }

    /**
     * Create an aliased <code>DFU_.Organize_</code> table reference
     */
    public Organize_(String alias) {
        this(DSL.name(alias), ORGANIZE_);
    }

    /**
     * Create an aliased <code>DFU_.Organize_</code> table reference
     */
    public Organize_(Name alias) {
        this(alias, ORGANIZE_);
    }

    private Organize_(Name alias, Table<Organize_Record> aliased) {
        this(alias, aliased, null);
    }

    private Organize_(Name alias, Table<Organize_Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "组织");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dfu_.DFU_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ORGANIZE__PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Organize_Record> getPrimaryKey() {
        return Keys.KEY_ORGANIZE__PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Organize_Record>> getKeys() {
        return Arrays.<UniqueKey<Organize_Record>>asList(Keys.KEY_ORGANIZE__PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Organize_ as(String alias) {
        return new Organize_(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Organize_ as(Name alias) {
        return new Organize_(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Organize_ rename(String name) {
        return new Organize_(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Organize_ rename(Name name) {
        return new Organize_(name, null);
    }
}
