/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables;


import cn.gatesma.desirefu.domain.db.generate.DFU_.Dfu_;
import cn.gatesma.desirefu.domain.db.generate.DFU_.Indexes;
import cn.gatesma.desirefu.domain.db.generate.DFU_.Keys;
import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records.User_Record;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User_ extends TableImpl<User_Record> {

    private static final long serialVersionUID = 3331478;

    /**
     * The reference instance of <code>dfu_.user_</code>
     */
    public static final User_ USER_ = new User_();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<User_Record> getRecordType() {
        return User_Record.class;
    }

    /**
     * The column <code>dfu_.user_.userId</code>. 用户ID
     */
    public final TableField<User_Record, Long> USERID = createField("userId", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "用户ID");

    /**
     * The column <code>dfu_.user_.userName</code>. userName
     */
    public final TableField<User_Record, String> USERNAME = createField("userName", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false).defaultValue(DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "userName");

    /**
     * The column <code>dfu_.user_.cellphone</code>. 手机号
     */
    public final TableField<User_Record, String> CELLPHONE = createField("cellphone", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "手机号");

    /**
     * The column <code>dfu_.user_.email</code>. 邮箱地址
     */
    public final TableField<User_Record, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "邮箱地址");

    /**
     * The column <code>dfu_.user_.createdTime</code>. 创建时间
     */
    public final TableField<User_Record, Timestamp> CREATEDTIME = createField("createdTime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "创建时间");

    /**
     * The column <code>dfu_.user_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public final TableField<User_Record, Integer> DELETESTATUS = createField("deleteStatus", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "删除状态，0-正常，1-删除");

    /**
     * The column <code>dfu_.user_.lastModifiedUserId</code>. 最后修改人userId
     */
    public final TableField<User_Record, Long> LASTMODIFIEDUSERID = createField("lastModifiedUserId", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "最后修改人userId");

    /**
     * The column <code>dfu_.user_.lastModifiedTime</code>. CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
     */
    public final TableField<User_Record, Timestamp> LASTMODIFIEDTIME = createField("lastModifiedTime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

    /**
     * The column <code>dfu_.user_.createdUserId</code>. 创建者userId
     */
    public final TableField<User_Record, Long> CREATEDUSERID = createField("createdUserId", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "创建者userId");

    /**
     * Create a <code>dfu_.user_</code> table reference
     */
    public User_() {
        this(DSL.name("user_"), null);
    }

    /**
     * Create an aliased <code>dfu_.user_</code> table reference
     */
    public User_(String alias) {
        this(DSL.name(alias), USER_);
    }

    /**
     * Create an aliased <code>dfu_.user_</code> table reference
     */
    public User_(Name alias) {
        this(alias, USER_);
    }

    private User_(Name alias, Table<User_Record> aliased) {
        this(alias, aliased, null);
    }

    private User_(Name alias, Table<User_Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dfu_.DFU_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER__PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<User_Record, Long> getIdentity() {
        return Keys.IDENTITY_USER_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<User_Record> getPrimaryKey() {
        return Keys.KEY_USER__PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<User_Record>> getKeys() {
        return Arrays.<UniqueKey<User_Record>>asList(Keys.KEY_USER__PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public User_ as(String alias) {
        return new User_(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public User_ as(Name alias) {
        return new User_(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public User_ rename(String name) {
        return new User_(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public User_ rename(Name name) {
        return new User_(name, null);
    }
}
