/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Collect_;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 收藏表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Collect_Record extends UpdatableRecordImpl<Collect_Record> implements Record6<Long, Long, Long, Timestamp, Integer, Timestamp> {

    private static final long serialVersionUID = 2096396598;

    /**
     * Setter for <code>DFU_.Collect_.id</code>. Id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>DFU_.Collect_.id</code>. Id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>DFU_.Collect_.accountId</code>. AccountID
     */
    public void setAccountid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>DFU_.Collect_.accountId</code>. AccountID
     */
    public Long getAccountid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DFU_.Collect_.competitionId</code>. 收藏的比赛ID
     */
    public void setCompetitionid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>DFU_.Collect_.competitionId</code>. 收藏的比赛ID
     */
    public Long getCompetitionid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>DFU_.Collect_.createdTime</code>. 创建时间
     */
    public void setCreatedtime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>DFU_.Collect_.createdTime</code>. 创建时间
     */
    public Timestamp getCreatedtime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>DFU_.Collect_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public void setDeletestatus(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>DFU_.Collect_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public Integer getDeletestatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>DFU_.Collect_.lastModifiedTime</code>. lastModifiedTime
     */
    public void setLastmodifiedtime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>DFU_.Collect_.lastModifiedTime</code>. lastModifiedTime
     */
    public Timestamp getLastmodifiedtime() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, Long, Timestamp, Integer, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, Long, Timestamp, Integer, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Collect_.COLLECT_.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Collect_.COLLECT_.ACCOUNTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Collect_.COLLECT_.COMPETITIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Collect_.COLLECT_.CREATEDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Collect_.COLLECT_.DELETESTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Collect_.COLLECT_.LASTMODIFIEDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getAccountid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getCompetitionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getDeletestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getLastmodifiedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAccountid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCompetitionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getDeletestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getLastmodifiedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Collect_Record value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Collect_Record value2(Long value) {
        setAccountid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Collect_Record value3(Long value) {
        setCompetitionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Collect_Record value4(Timestamp value) {
        setCreatedtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Collect_Record value5(Integer value) {
        setDeletestatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Collect_Record value6(Timestamp value) {
        setLastmodifiedtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Collect_Record values(Long value1, Long value2, Long value3, Timestamp value4, Integer value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Collect_Record
     */
    public Collect_Record() {
        super(Collect_.COLLECT_);
    }

    /**
     * Create a detached, initialised Collect_Record
     */
    public Collect_Record(Long id, Long accountid, Long competitionid, Timestamp createdtime, Integer deletestatus, Timestamp lastmodifiedtime) {
        super(Collect_.COLLECT_);

        set(0, id);
        set(1, accountid);
        set(2, competitionid);
        set(3, createdtime);
        set(4, deletestatus);
        set(5, lastmodifiedtime);
    }
}
