/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.College_;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 高校信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class College_Record extends UpdatableRecordImpl<College_Record> implements Record10<Integer, String, String, String, String, String, String, Timestamp, Integer, Timestamp> {

    private static final long serialVersionUID = -897428649;

    /**
     * Setter for <code>dfu_.college_.collegeId</code>. 学校Id
     */
    public void setCollegeid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dfu_.college_.collegeId</code>. 学校Id
     */
    public Integer getCollegeid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dfu_.college_.name</code>. 学校名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dfu_.college_.name</code>. 学校名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dfu_.college_.ministry</code>. 主管部门
     */
    public void setMinistry(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dfu_.college_.ministry</code>. 主管部门
     */
    public String getMinistry() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dfu_.college_.identification</code>. 学校标识码
     */
    public void setIdentification(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dfu_.college_.identification</code>. 学校标识码
     */
    public String getIdentification() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dfu_.college_.location</code>. 所在地
     */
    public void setLocation(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>dfu_.college_.location</code>. 所在地
     */
    public String getLocation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>dfu_.college_.level</code>. 办学层次
     */
    public void setLevel(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>dfu_.college_.level</code>. 办学层次
     */
    public String getLevel() {
        return (String) get(5);
    }

    /**
     * Setter for <code>dfu_.college_.memo</code>. 备注
     */
    public void setMemo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>dfu_.college_.memo</code>. 备注
     */
    public String getMemo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>dfu_.college_.createdTime</code>. 创建时间
     */
    public void setCreatedtime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>dfu_.college_.createdTime</code>. 创建时间
     */
    public Timestamp getCreatedtime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>dfu_.college_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public void setDeletestatus(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>dfu_.college_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public Integer getDeletestatus() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>dfu_.college_.lastModifiedTime</code>. lastModifiedTime
     */
    public void setLastmodifiedtime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>dfu_.college_.lastModifiedTime</code>. lastModifiedTime
     */
    public Timestamp getLastmodifiedtime() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, String, Timestamp, Integer, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, String, Timestamp, Integer, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return College_.COLLEGE_.COLLEGEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return College_.COLLEGE_.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return College_.COLLEGE_.MINISTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return College_.COLLEGE_.IDENTIFICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return College_.COLLEGE_.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return College_.COLLEGE_.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return College_.COLLEGE_.MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return College_.COLLEGE_.CREATEDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return College_.COLLEGE_.DELETESTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return College_.COLLEGE_.LASTMODIFIEDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCollegeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMinistry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getIdentification();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreatedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getDeletestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getLastmodifiedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCollegeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMinistry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIdentification();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getDeletestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getLastmodifiedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public College_Record value1(Integer value) {
        setCollegeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public College_Record value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public College_Record value3(String value) {
        setMinistry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public College_Record value4(String value) {
        setIdentification(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public College_Record value5(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public College_Record value6(String value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public College_Record value7(String value) {
        setMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public College_Record value8(Timestamp value) {
        setCreatedtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public College_Record value9(Integer value) {
        setDeletestatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public College_Record value10(Timestamp value) {
        setLastmodifiedtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public College_Record values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Timestamp value8, Integer value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached College_Record
     */
    public College_Record() {
        super(College_.COLLEGE_);
    }

    /**
     * Create a detached, initialised College_Record
     */
    public College_Record(Integer collegeid, String name, String ministry, String identification, String location, String level, String memo, Timestamp createdtime, Integer deletestatus, Timestamp lastmodifiedtime) {
        super(College_.COLLEGE_);

        set(0, collegeid);
        set(1, name);
        set(2, ministry);
        set(3, identification);
        set(4, location);
        set(5, level);
        set(6, memo);
        set(7, createdtime);
        set(8, deletestatus);
        set(9, lastmodifiedtime);
    }
}
