/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Competitionvisible_;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 高校可见比赛表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Competitionvisible_Record extends UpdatableRecordImpl<Competitionvisible_Record> implements Record5<Integer, Long, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 431274255;

    /**
     * Setter for <code>DFU_.CompetitionVisible_.collegeId</code>. 高校ID
     */
    public void setCollegeid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DFU_.CompetitionVisible_.collegeId</code>. 高校ID
     */
    public Integer getCollegeid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DFU_.CompetitionVisible_.competitionId</code>. 帐号ID
     */
    public void setCompetitionid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>DFU_.CompetitionVisible_.competitionId</code>. 帐号ID
     */
    public Long getCompetitionid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DFU_.CompetitionVisible_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public void setDeletestatus(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>DFU_.CompetitionVisible_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public Integer getDeletestatus() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>DFU_.CompetitionVisible_.createdTime</code>. 创建时间
     */
    public void setCreatedtime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>DFU_.CompetitionVisible_.createdTime</code>. 创建时间
     */
    public Timestamp getCreatedtime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>DFU_.CompetitionVisible_.lastModifiedTime</code>. lastModifiedTime
     */
    public void setLastmodifiedtime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>DFU_.CompetitionVisible_.lastModifiedTime</code>. lastModifiedTime
     */
    public Timestamp getLastmodifiedtime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Long, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Long, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Competitionvisible_.COMPETITIONVISIBLE_.COLLEGEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Competitionvisible_.COMPETITIONVISIBLE_.COMPETITIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Competitionvisible_.COMPETITIONVISIBLE_.DELETESTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Competitionvisible_.COMPETITIONVISIBLE_.CREATEDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Competitionvisible_.COMPETITIONVISIBLE_.LASTMODIFIEDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCollegeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getCompetitionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDeletestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getLastmodifiedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCollegeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCompetitionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDeletestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLastmodifiedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competitionvisible_Record value1(Integer value) {
        setCollegeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competitionvisible_Record value2(Long value) {
        setCompetitionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competitionvisible_Record value3(Integer value) {
        setDeletestatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competitionvisible_Record value4(Timestamp value) {
        setCreatedtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competitionvisible_Record value5(Timestamp value) {
        setLastmodifiedtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competitionvisible_Record values(Integer value1, Long value2, Integer value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Competitionvisible_Record
     */
    public Competitionvisible_Record() {
        super(Competitionvisible_.COMPETITIONVISIBLE_);
    }

    /**
     * Create a detached, initialised Competitionvisible_Record
     */
    public Competitionvisible_Record(Integer collegeid, Long competitionid, Integer deletestatus, Timestamp createdtime, Timestamp lastmodifiedtime) {
        super(Competitionvisible_.COMPETITIONVISIBLE_);

        set(0, collegeid);
        set(1, competitionid);
        set(2, deletestatus);
        set(3, createdtime);
        set(4, lastmodifiedtime);
    }
}
