/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Competition_;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 比赛
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Competition_Record extends UpdatableRecordImpl<Competition_Record> implements Record15<Long, Long, Integer, Integer, String, String, String, Integer, Timestamp, Timestamp, Integer, Long, Timestamp, Long, Timestamp> {

    private static final long serialVersionUID = -1578296944;

    /**
     * Setter for <code>DFU_.Competition_.competitionId</code>. 帐号ID
     */
    public void setCompetitionid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>DFU_.Competition_.competitionId</code>. 帐号ID
     */
    public Long getCompetitionid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>DFU_.Competition_.accountId</code>. 比赛归属帐号ID
     */
    public void setAccountid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>DFU_.Competition_.accountId</code>. 比赛归属帐号ID
     */
    public Long getAccountid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DFU_.Competition_.accountType</code>. 比赛归属账号类型
     */
    public void setAccounttype(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>DFU_.Competition_.accountType</code>. 比赛归属账号类型
     */
    public Integer getAccounttype() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>DFU_.Competition_.type</code>. 比赛类型 - 省级、校级等
     */
    public void setType(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>DFU_.Competition_.type</code>. 比赛类型 - 省级、校级等
     */
    public Integer getType() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>DFU_.Competition_.title</code>. 比赛名称
     */
    public void setTitle(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>DFU_.Competition_.title</code>. 比赛名称
     */
    public String getTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DFU_.Competition_.founder</code>. 创办方
     */
    public void setFounder(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DFU_.Competition_.founder</code>. 创办方
     */
    public String getFounder() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DFU_.Competition_.content</code>. 具体通知内容，富文本
     */
    public void setContent(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DFU_.Competition_.content</code>. 具体通知内容，富文本
     */
    public String getContent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DFU_.Competition_.pv</code>. 浏览人数
     */
    public void setPv(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>DFU_.Competition_.pv</code>. 浏览人数
     */
    public Integer getPv() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>DFU_.Competition_.beginTime</code>. 比赛开始时间
     */
    public void setBegintime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>DFU_.Competition_.beginTime</code>. 比赛开始时间
     */
    public Timestamp getBegintime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>DFU_.Competition_.endTime</code>. 比赛结束时间
     */
    public void setEndtime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>DFU_.Competition_.endTime</code>. 比赛结束时间
     */
    public Timestamp getEndtime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>DFU_.Competition_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public void setDeletestatus(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>DFU_.Competition_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public Integer getDeletestatus() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>DFU_.Competition_.createdUserId</code>. 创建人userId
     */
    public void setCreateduserid(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>DFU_.Competition_.createdUserId</code>. 创建人userId
     */
    public Long getCreateduserid() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>DFU_.Competition_.createdTime</code>. 创建时间
     */
    public void setCreatedtime(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>DFU_.Competition_.createdTime</code>. 创建时间
     */
    public Timestamp getCreatedtime() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>DFU_.Competition_.lastModifiedUserId</code>. 最后修改人userId
     */
    public void setLastmodifieduserid(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>DFU_.Competition_.lastModifiedUserId</code>. 最后修改人userId
     */
    public Long getLastmodifieduserid() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>DFU_.Competition_.lastModifiedTime</code>. lastModifiedTime
     */
    public void setLastmodifiedtime(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>DFU_.Competition_.lastModifiedTime</code>. lastModifiedTime
     */
    public Timestamp getLastmodifiedtime() {
        return (Timestamp) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Long, Long, Integer, Integer, String, String, String, Integer, Timestamp, Timestamp, Integer, Long, Timestamp, Long, Timestamp> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Long, Long, Integer, Integer, String, String, String, Integer, Timestamp, Timestamp, Integer, Long, Timestamp, Long, Timestamp> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Competition_.COMPETITION_.COMPETITIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Competition_.COMPETITION_.ACCOUNTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Competition_.COMPETITION_.ACCOUNTTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Competition_.COMPETITION_.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Competition_.COMPETITION_.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Competition_.COMPETITION_.FOUNDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Competition_.COMPETITION_.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Competition_.COMPETITION_.PV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Competition_.COMPETITION_.BEGINTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Competition_.COMPETITION_.ENDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Competition_.COMPETITION_.DELETESTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return Competition_.COMPETITION_.CREATEDUSERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return Competition_.COMPETITION_.CREATEDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field14() {
        return Competition_.COMPETITION_.LASTMODIFIEDUSERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return Competition_.COMPETITION_.LASTMODIFIEDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getCompetitionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getAccountid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getAccounttype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getFounder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getPv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getBegintime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getEndtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getDeletestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getCreateduserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getCreatedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component14() {
        return getLastmodifieduserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component15() {
        return getLastmodifiedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getCompetitionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAccountid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAccounttype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFounder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getPv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getBegintime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getEndtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getDeletestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getCreateduserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getCreatedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value14() {
        return getLastmodifieduserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getLastmodifiedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record value1(Long value) {
        setCompetitionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record value2(Long value) {
        setAccountid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record value3(Integer value) {
        setAccounttype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record value4(Integer value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record value5(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record value6(String value) {
        setFounder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record value7(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record value8(Integer value) {
        setPv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record value9(Timestamp value) {
        setBegintime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record value10(Timestamp value) {
        setEndtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record value11(Integer value) {
        setDeletestatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record value12(Long value) {
        setCreateduserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record value13(Timestamp value) {
        setCreatedtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record value14(Long value) {
        setLastmodifieduserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record value15(Timestamp value) {
        setLastmodifiedtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition_Record values(Long value1, Long value2, Integer value3, Integer value4, String value5, String value6, String value7, Integer value8, Timestamp value9, Timestamp value10, Integer value11, Long value12, Timestamp value13, Long value14, Timestamp value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Competition_Record
     */
    public Competition_Record() {
        super(Competition_.COMPETITION_);
    }

    /**
     * Create a detached, initialised Competition_Record
     */
    public Competition_Record(Long competitionid, Long accountid, Integer accounttype, Integer type, String title, String founder, String content, Integer pv, Timestamp begintime, Timestamp endtime, Integer deletestatus, Long createduserid, Timestamp createdtime, Long lastmodifieduserid, Timestamp lastmodifiedtime) {
        super(Competition_.COMPETITION_);

        set(0, competitionid);
        set(1, accountid);
        set(2, accounttype);
        set(3, type);
        set(4, title);
        set(5, founder);
        set(6, content);
        set(7, pv);
        set(8, begintime);
        set(9, endtime);
        set(10, deletestatus);
        set(11, createduserid);
        set(12, createdtime);
        set(13, lastmodifieduserid);
        set(14, lastmodifiedtime);
    }
}
