/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Department_;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 学院信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Department_Record extends UpdatableRecordImpl<Department_Record> implements Record6<Integer, Integer, String, Timestamp, Integer, Timestamp> {

    private static final long serialVersionUID = 43413615;

    /**
     * Setter for <code>DFU_.Department_.departmentId</code>. 学院Id
     */
    public void setDepartmentid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DFU_.Department_.departmentId</code>. 学院Id
     */
    public Integer getDepartmentid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DFU_.Department_.collegeId</code>. 高校id
     */
    public void setCollegeid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>DFU_.Department_.collegeId</code>. 高校id
     */
    public Integer getCollegeid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>DFU_.Department_.name</code>. 学院名称
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DFU_.Department_.name</code>. 学院名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DFU_.Department_.createdTime</code>. 创建时间
     */
    public void setCreatedtime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>DFU_.Department_.createdTime</code>. 创建时间
     */
    public Timestamp getCreatedtime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>DFU_.Department_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public void setDeletestatus(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>DFU_.Department_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public Integer getDeletestatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>DFU_.Department_.lastModifiedTime</code>. lastModifiedTime
     */
    public void setLastmodifiedtime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>DFU_.Department_.lastModifiedTime</code>. lastModifiedTime
     */
    public Timestamp getLastmodifiedtime() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, Timestamp, Integer, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, Timestamp, Integer, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Department_.DEPARTMENT_.DEPARTMENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Department_.DEPARTMENT_.COLLEGEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Department_.DEPARTMENT_.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Department_.DEPARTMENT_.CREATEDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Department_.DEPARTMENT_.DELETESTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Department_.DEPARTMENT_.LASTMODIFIEDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getDepartmentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCollegeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getDeletestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getLastmodifiedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getDepartmentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCollegeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getDeletestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getLastmodifiedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Department_Record value1(Integer value) {
        setDepartmentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Department_Record value2(Integer value) {
        setCollegeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Department_Record value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Department_Record value4(Timestamp value) {
        setCreatedtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Department_Record value5(Integer value) {
        setDeletestatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Department_Record value6(Timestamp value) {
        setLastmodifiedtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Department_Record values(Integer value1, Integer value2, String value3, Timestamp value4, Integer value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Department_Record
     */
    public Department_Record() {
        super(Department_.DEPARTMENT_);
    }

    /**
     * Create a detached, initialised Department_Record
     */
    public Department_Record(Integer departmentid, Integer collegeid, String name, Timestamp createdtime, Integer deletestatus, Timestamp lastmodifiedtime) {
        super(Department_.DEPARTMENT_);

        set(0, departmentid);
        set(1, collegeid);
        set(2, name);
        set(3, createdtime);
        set(4, deletestatus);
        set(5, lastmodifiedtime);
    }
}
