/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Normalaccount_;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Normalaccount_Record extends UpdatableRecordImpl<Normalaccount_Record> implements Record10<Long, Integer, Integer, Integer, String, Long, Timestamp, Integer, Long, Timestamp> {

    private static final long serialVersionUID = 806632169;

    /**
     * Setter for <code>dfu_.normalaccount_.accountId</code>. 帐号ID
     */
    public void setAccountid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>dfu_.normalaccount_.accountId</code>. 帐号ID
     */
    public Long getAccountid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>dfu_.normalaccount_.accountType</code>. 账号类型
     */
    public void setAccounttype(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dfu_.normalaccount_.accountType</code>. 账号类型
     */
    public Integer getAccounttype() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dfu_.normalaccount_.collegeId</code>. 学校Id
     */
    public void setCollegeid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>dfu_.normalaccount_.collegeId</code>. 学校Id
     */
    public Integer getCollegeid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>dfu_.normalaccount_.departmentId</code>. 学院Id
     */
    public void setDepartmentid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>dfu_.normalaccount_.departmentId</code>. 学院Id
     */
    public Integer getDepartmentid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>dfu_.normalaccount_.major</code>. 专业
     */
    public void setMajor(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>dfu_.normalaccount_.major</code>. 专业
     */
    public String getMajor() {
        return (String) get(4);
    }

    /**
     * Setter for <code>dfu_.normalaccount_.createdUserId</code>. 创建人userId
     */
    public void setCreateduserid(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>dfu_.normalaccount_.createdUserId</code>. 创建人userId
     */
    public Long getCreateduserid() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>dfu_.normalaccount_.createdTime</code>. 创建时间
     */
    public void setCreatedtime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>dfu_.normalaccount_.createdTime</code>. 创建时间
     */
    public Timestamp getCreatedtime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>dfu_.normalaccount_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public void setDeletestatus(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>dfu_.normalaccount_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public Integer getDeletestatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>dfu_.normalaccount_.lastModifiedUserId</code>. 最后修改人userId
     */
    public void setLastmodifieduserid(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>dfu_.normalaccount_.lastModifiedUserId</code>. 最后修改人userId
     */
    public Long getLastmodifieduserid() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>dfu_.normalaccount_.lastModifiedTime</code>. lastModifiedTime
     */
    public void setLastmodifiedtime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>dfu_.normalaccount_.lastModifiedTime</code>. lastModifiedTime
     */
    public Timestamp getLastmodifiedtime() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Integer, Integer, Integer, String, Long, Timestamp, Integer, Long, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Integer, Integer, Integer, String, Long, Timestamp, Integer, Long, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Normalaccount_.NORMALACCOUNT_.ACCOUNTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Normalaccount_.NORMALACCOUNT_.ACCOUNTTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Normalaccount_.NORMALACCOUNT_.COLLEGEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Normalaccount_.NORMALACCOUNT_.DEPARTMENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Normalaccount_.NORMALACCOUNT_.MAJOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Normalaccount_.NORMALACCOUNT_.CREATEDUSERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Normalaccount_.NORMALACCOUNT_.CREATEDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Normalaccount_.NORMALACCOUNT_.DELETESTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Normalaccount_.NORMALACCOUNT_.LASTMODIFIEDUSERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Normalaccount_.NORMALACCOUNT_.LASTMODIFIEDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getAccountid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getAccounttype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCollegeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getDepartmentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMajor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getCreateduserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreatedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getDeletestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getLastmodifieduserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getLastmodifiedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getAccountid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAccounttype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCollegeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getDepartmentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMajor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getCreateduserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getDeletestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getLastmodifieduserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getLastmodifiedtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Normalaccount_Record value1(Long value) {
        setAccountid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Normalaccount_Record value2(Integer value) {
        setAccounttype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Normalaccount_Record value3(Integer value) {
        setCollegeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Normalaccount_Record value4(Integer value) {
        setDepartmentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Normalaccount_Record value5(String value) {
        setMajor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Normalaccount_Record value6(Long value) {
        setCreateduserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Normalaccount_Record value7(Timestamp value) {
        setCreatedtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Normalaccount_Record value8(Integer value) {
        setDeletestatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Normalaccount_Record value9(Long value) {
        setLastmodifieduserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Normalaccount_Record value10(Timestamp value) {
        setLastmodifiedtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Normalaccount_Record values(Long value1, Integer value2, Integer value3, Integer value4, String value5, Long value6, Timestamp value7, Integer value8, Long value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Normalaccount_Record
     */
    public Normalaccount_Record() {
        super(Normalaccount_.NORMALACCOUNT_);
    }

    /**
     * Create a detached, initialised Normalaccount_Record
     */
    public Normalaccount_Record(Long accountid, Integer accounttype, Integer collegeid, Integer departmentid, String major, Long createduserid, Timestamp createdtime, Integer deletestatus, Long lastmodifieduserid, Timestamp lastmodifiedtime) {
        super(Normalaccount_.NORMALACCOUNT_);

        set(0, accountid);
        set(1, accounttype);
        set(2, collegeid);
        set(3, departmentid);
        set(4, major);
        set(5, createduserid);
        set(6, createdtime);
        set(7, deletestatus);
        set(8, lastmodifieduserid);
        set(9, lastmodifiedtime);
    }
}
