/*
 * This file is generated by jOOQ.
*/
package cn.gatesma.desirefu.domain.db.generate.DFU_.tables.records;


import cn.gatesma.desirefu.domain.db.generate.DFU_.tables.Openidqqidx_;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用于存储openId对应qq关联关系
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Openidqqidx_Record extends UpdatableRecordImpl<Openidqqidx_Record> implements Record3<String, String, Integer> {

    private static final long serialVersionUID = -85350011;

    /**
     * Setter for <code>DFU_.OpenIdQQIdx_.openId</code>. qq对应生成的openId
     */
    public void setOpenid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DFU_.OpenIdQQIdx_.openId</code>. qq对应生成的openId
     */
    public String getOpenid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DFU_.OpenIdQQIdx_.qqNumber</code>. qq号
     */
    public void setQqnumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DFU_.OpenIdQQIdx_.qqNumber</code>. qq号
     */
    public String getQqnumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DFU_.OpenIdQQIdx_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public void setDeletestatus(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>DFU_.OpenIdQQIdx_.deleteStatus</code>. 删除状态，0-正常，1-删除
     */
    public Integer getDeletestatus() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Openidqqidx_.OPENIDQQIDX_.OPENID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Openidqqidx_.OPENIDQQIDX_.QQNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Openidqqidx_.OPENIDQQIDX_.DELETESTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getQqnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDeletestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getQqnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDeletestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Openidqqidx_Record value1(String value) {
        setOpenid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Openidqqidx_Record value2(String value) {
        setQqnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Openidqqidx_Record value3(Integer value) {
        setDeletestatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Openidqqidx_Record values(String value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Openidqqidx_Record
     */
    public Openidqqidx_Record() {
        super(Openidqqidx_.OPENIDQQIDX_);
    }

    /**
     * Create a detached, initialised Openidqqidx_Record
     */
    public Openidqqidx_Record(String openid, String qqnumber, Integer deletestatus) {
        super(Openidqqidx_.OPENIDQQIDX_);

        set(0, openid);
        set(1, qqnumber);
        set(2, deletestatus);
    }
}
